# Author : Prashanta Pal

# Model : Hate Speech Detection by LSTM

In [1]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset,DataLoader
import torch.optim as optim
from collections import Counter
from nltk import word_tokenize
import nltk

In [2]:
import kagglehub
import os

# Download latest version
path = kagglehub.dataset_download("mrmorj/hate-speech-and-offensive-language-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/mrmorj/hate-speech-and-offensive-language-dataset/1.archive...

100%|██████████| 1.01M/1.01M [00:00<00:00, 92.0MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/mrmorj/hate-speech-and-offensive-language-dataset/versions/1

In [10]:
# Load CSV file
df = pd.read_csv(
    os.path.join(path, "labeled_data.csv")
)

# Show first rows
print(df.head())

   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2
1           1      3            0                   3        0      1
2           2      3            0                   3        0      1
3           3      3            0                   2        1      1
4           4      6            0                   6        0      1

                                               tweet
0  !!! RT @mayasolovely: As a woman you shouldn't...
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...

In [4]:
df.shape

(24783, 7)

In [5]:
sub_df=df.sample(n=600)

In [9]:
sub_df

,Unnamed: 0,count,hate_speech,offensive_language,neither,class,tweet
8864,9110,6,0,6,0,1,Drop it down for a niggah
395,400,3,1,0,2,2,"""@socass_: Dude remember this wop video? @00se..."
898,917,3,0,3,0,1,"#porn,#android,#iphone,#ipad,#sex,#xxx, | #Mas..."
20248,20693,3,0,3,0,1,RT @tupactopus: need a bad bitch who knows how...
14588,14937,3,0,3,0,1,RT @Cam_Major: naw no bs tho...if u under lets...
...,...,...,...,...,...,...,...
20970,21421,3,0,0,3,2,"So my light was off &amp; door was closed , mo..."
14199,14540,3,0,3,0,1,RT @Annnna_dav69: Ima make you my bitch &#128521;
6189,6366,3,1,2,0,1,@itsjustmexo ur a cunt nd a wish a was a faggot
18325,18732,3,0,0,3,2,RT @_MykalaJ: @whitakerc54 blame it on the yel...
19405,19835,6,1,5,0,1,RT @karlos_budah: @RealNiggaSherm aye bro you ...

In [7]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [14]:
sub_df.drop(columns=["Unnamed: 0" , "count",  "hate_speech",  "offensive_language",  "neither"],inplace=True)

In [21]:
sub_df["cleaned_tweet"]=sub_df["tweet"].str.replace(r"[^a-zA-z]"," ",regex=True)

In [22]:
sub_df

,class,tweet,cleaned_tweet
8864,1,Drop it down for a niggah,Drop it down for a niggah
395,2,"""@socass_: Dude remember this wop video? @00se...",socass_ Dude remember this wop video se...
898,1,"#porn,#android,#iphone,#ipad,#sex,#xxx, | #Mas...",porn android iphone ipad sex xxx Mas...
20248,1,RT @tupactopus: need a bad bitch who knows how...,RT tupactopus need a bad bitch who knows how...
14588,1,RT @Cam_Major: naw no bs tho...if u under lets...,RT Cam_Major naw no bs tho if u under lets...
...,...,...,...
20970,2,"So my light was off &amp; door was closed , mo...",So my light was off amp door was closed mo...
14199,1,RT @Annnna_dav69: Ima make you my bitch &#128521;,RT Annnna_dav Ima make you my bitch
6189,1,@itsjustmexo ur a cunt nd a wish a was a faggot,itsjustmexo ur a cunt nd a wish a was a faggot
18325,2,RT @_MykalaJ: @whitakerc54 blame it on the yel...,RT _MykalaJ whitakerc blame it on the yel...
19405,1,RT @karlos_budah: @RealNiggaSherm aye bro you ...,RT karlos_budah RealNiggaSherm aye bro you ...

In [23]:
sub_df["cleaned_tweet"]=sub_df["cleaned_tweet"].str.replace(r"[\s]+"," ",regex=True)

In [24]:
sub_df

,class,tweet,cleaned_tweet
8864,1,Drop it down for a niggah,Drop it down for a niggah
395,2,"""@socass_: Dude remember this wop video? @00se...",socass_ Dude remember this wop video sexilexi...
898,1,"#porn,#android,#iphone,#ipad,#sex,#xxx, | #Mas...",porn android iphone ipad sex xxx Masturbation...
20248,1,RT @tupactopus: need a bad bitch who knows how...,RT tupactopus need a bad bitch who knows how t...
14588,1,RT @Cam_Major: naw no bs tho...if u under lets...,RT Cam_Major naw no bs tho if u under lets say...
...,...,...,...
20970,2,"So my light was off &amp; door was closed , mo...",So my light was off amp door was closed mom wa...
14199,1,RT @Annnna_dav69: Ima make you my bitch &#128521;,RT Annnna_dav Ima make you my bitch
6189,1,@itsjustmexo ur a cunt nd a wish a was a faggot,itsjustmexo ur a cunt nd a wish a was a faggot
18325,2,RT @_MykalaJ: @whitakerc54 blame it on the yel...,RT _MykalaJ whitakerc blame it on the yellow c...
19405,1,RT @karlos_budah: @RealNiggaSherm aye bro you ...,RT karlos_budah RealNiggaSherm aye bro you kno...

In [27]:
sub_df.drop(columns=["tweet"],inplace=True)

In [28]:
sub_df

       class                                      cleaned_tweet
8864       1                          Drop it down for a niggah
395        2   socass_ Dude remember this wop video sexilexi...
898        1   porn android iphone ipad sex xxx Masturbation...
20248      1  RT tupactopus need a bad bitch who knows how t...
14588      1  RT Cam_Major naw no bs tho if u under lets say...
...      ...                                                ...
20970      2  So my light was off amp door was closed mom wa...
14199      1               RT Annnna_dav Ima make you my bitch
6189       1     itsjustmexo ur a cunt nd a wish a was a faggot
18325      2  RT _MykalaJ whitakerc blame it on the yellow c...
19405      1  RT karlos_budah RealNiggaSherm aye bro you kno...

[600 rows x 2 columns]

# Lemmatization ( Converting into Base Words)

In [29]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [34]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [31]:
def lemmatization(text):
  tokens = word_tokenize(text)

  lemmatizer = WordNetLemmatizer()

  lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

  return " ".join(lemmatized_words)

In [35]:
sub_df["lemma_tweets"]=sub_df["cleaned_tweet"].apply(lemmatization)

In [36]:
sub_df

,class,cleaned_tweet,lemma_tweets
8864,1,Drop it down for a niggah,Drop it down for a niggah
395,2,socass_ Dude remember this wop video sexilexi...,socass_ Dude remember this wop video sexilexi ...
898,1,porn android iphone ipad sex xxx Masturbation...,porn android iphone ipad sex xxx Masturbation ...
20248,1,RT tupactopus need a bad bitch who knows how t...,RT tupactopus need a bad bitch who know how tr...
14588,1,RT Cam_Major naw no bs tho if u under lets say...,RT Cam_Major naw no b tho if u under let say a...
...,...,...,...
20970,2,So my light was off amp door was closed mom wa...,So my light wa off amp door wa closed mom walk...
14199,1,RT Annnna_dav Ima make you my bitch,RT Annnna_dav Ima make you my bitch
6189,1,itsjustmexo ur a cunt nd a wish a was a faggot,itsjustmexo ur a cunt nd a wish a wa a faggot
18325,2,RT _MykalaJ whitakerc blame it on the yellow c...,RT _MykalaJ whitakerc blame it on the yellow c...
19405,1,RT karlos_budah RealNiggaSherm aye bro you kno...,RT karlos_budah RealNiggaSherm aye bro you kno...

In [37]:
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [38]:
def stop_words(text):
  stop_words = set(stopwords.words('english'))
  tokens = word_tokenize(text)
  filtered = [
    word for word in tokens
    if word.lower() not in stop_words
  ]
  return " ".join(filtered)

In [39]:
sub_df["final_tweets"]=sub_df["lemma_tweets"].apply(lemmatization)

In [40]:
sub_df

,class,cleaned_tweet,lemma_tweets,final_tweets
8864,1,Drop it down for a niggah,Drop it down for a niggah,Drop it down for a niggah
395,2,socass_ Dude remember this wop video sexilexi...,socass_ Dude remember this wop video sexilexi ...,socass_ Dude remember this wop video sexilexi ...
898,1,porn android iphone ipad sex xxx Masturbation...,porn android iphone ipad sex xxx Masturbation ...,porn android iphone ipad sex xxx Masturbation ...
20248,1,RT tupactopus need a bad bitch who knows how t...,RT tupactopus need a bad bitch who know how tr...,RT tupactopus need a bad bitch who know how tr...
14588,1,RT Cam_Major naw no bs tho if u under lets say...,RT Cam_Major naw no b tho if u under let say a...,RT Cam_Major naw no b tho if u under let say a...
...,...,...,...,...
20970,2,So my light was off amp door was closed mom wa...,So my light wa off amp door wa closed mom walk...,So my light wa off amp door wa closed mom walk...
14199,1,RT Annnna_dav Ima make you my bitch,RT Annnna_dav Ima make you my bitch,RT Annnna_dav Ima make you my bitch
6189,1,itsjustmexo ur a cunt nd a wish a was a faggot,itsjustmexo ur a cunt nd a wish a wa a faggot,itsjustmexo ur a cunt nd a wish a wa a faggot
18325,2,RT _MykalaJ whitakerc blame it on the yellow c...,RT _MykalaJ whitakerc blame it on the yellow c...,RT _MykalaJ whitakerc blame it on the yellow c...
19405,1,RT karlos_budah RealNiggaSherm aye bro you kno...,RT karlos_budah RealNiggaSherm aye bro you kno...,RT karlos_budah RealNiggaSherm aye bro you kno...

# Word Embeddings

In [44]:
# Create Tokens
token=[]
for text in sub_df["final_tweets"]:
  text = str(text)
  words=word_tokenize(text)
  token.extend(words)

In [45]:
token

['Drop',
 'it',
 'down',
 'for',
 'a',
 'niggah',
 'socass_',
 'Dude',
 'remember',
 'this',
 'wop',
 'video',
 'sexilexi',
 'http',
 't',
 'co',
 'P',
 'HEuBOQBu',
 'OMG',
 'WHERE',
 'DID',
 'YOU',
 'FIND',
 'THAT',
 'porn',
 'android',
 'iphone',
 'ipad',
 'sex',
 'xxx',
 'Masturbation',
 'A',
 'very',
 'hot',
 'black',
 'tranny',
 'is',
 'mastu',
 'http',
 't',
 'co',
 'OfGGMLXQAj',
 'RT',
 'tupactopus',
 'need',
 'a',
 'bad',
 'bitch',
 'who',
 'know',
 'how',
 'treat',
 'a',
 'pokemon',
 'master',
 'right',
 'RT',
 'Cam_Major',
 'naw',
 'no',
 'b',
 'tho',
 'if',
 'u',
 'under',
 'let',
 'say',
 'and',
 'u',
 'got',
 'like',
 'body',
 'u',
 'def',
 'a',
 'hoe',
 'lol',
 'there',
 'no',
 'debating',
 'that',
 'Let',
 'me',
 'text',
 'my',
 'hoe',
 'gm',
 'or',
 'sumpin',
 'RT',
 'sofancyy_',
 'A',
 'hoe',
 'gone',
 'be',
 'a',
 'hoe',
 'RT',
 'Thad_CastIe',
 'Regrets',
 'are',
 'for',
 'pussy',
 'Shit',
 'happens',
 'deal',
 'with',
 'it',
 'BITCH',
 'RT',
 'jla_b',
 'Stop',
 'thinking',
 'ur',
 'entitled',
 'to',
 'politically',
 'correct',
 'response',
 'bitch',
 'Black',
 'twitter',
 'need',
 'to',
 'get',
 'off',
 'Paul',
 'George',
 'dick',
 'about',
 'him',
 'impregnating',
 'a',
 'stripper',
 'Wiz',
 'did',
 'Tyga',
 'did',
 'Kanye',
 'turned',
 'a',
 'hoe',
 'into',
 'a',
 'housewife',
 'Melo',
 'should',
 've',
 'got',
 'the',
 'bitch',
 'for',
 'the',
 'east',
 'is',
 'now',
 'tweeting',
 'from',
 'a',
 'tablet',
 'baller',
 'bitch',
 'I',
 'didn',
 't',
 'forsake',
 'all',
 'other',
 'bitch',
 'for',
 'my',
 'wife',
 'to',
 'be',
 'getting',
 'fucked',
 'on',
 'by',
 'another',
 'nigga',
 'and',
 'you',
 'know',
 'she',
 'married',
 'you',
 'got',
 'ta',
 'die',
 'verkannt__',
 'what_evaittakes',
 'Nasty',
 'pay',
 'the',
 'bill',
 'bitch',
 'DanWolken',
 'It',
 's',
 'idiotic',
 'opinion',
 'like',
 'this',
 'that',
 'make',
 'poll',
 'less',
 'than',
 'trash',
 'Polls',
 'weren',
 't',
 'a',
 'problem',
 'when',
 'people',
 'with',
 'integrity',
 'were',
 'voting',
 'Why',
 'would',
 'I',
 'fuck',
 'a',
 'bitch',
 'that',
 'can',
 't',
 'fuck',
 'Jus',
 'like',
 'u',
 'hoe',
 'don',
 't',
 'want',
 'want',
 'a',
 'nigga',
 'wit',
 'a',
 'clit',
 'ticckler',
 'RT',
 'lildickytweets',
 'Eugene',
 'come',
 'watch',
 'me',
 'run',
 'circle',
 'round',
 'the',
 'rap',
 'game',
 'like',
 'my',
 'name',
 'wa',
 'chip',
 'kelly',
 'in',
 'this',
 'bitch',
 'http',
 't',
 'co',
 'kJzH',
 'U',
 'uSz',
 'h',
 'YessMe_SHAY',
 'I',
 'want',
 'my',
 'pom',
 'back',
 'lmfao',
 'mikecheck_',
 'the',
 'favorite',
 'drink',
 'of',
 'white',
 'trash',
 'everywhere',
 'JoriBunni',
 'he',
 'talkin',
 'bout',
 'we',
 'wan',
 'na',
 'be',
 'human',
 'and',
 'I',
 'm',
 'just',
 'like',
 'bitch',
 'whet',
 'Tf',
 'I',
 'm',
 'acting',
 'like',
 'a',
 'sad',
 'a',
 'bitch',
 'for',
 'Old',
 'Anthony',
 'coming',
 'back',
 'fashoo',
 'heyrmbr',
 'I',
 'never',
 'played',
 'Halo',
 'too',
 'busy',
 'slaying',
 'bitch',
 'It',
 's',
 'my',
 'man',
 'weaselfbaby',
 'birthday',
 'All',
 'the',
 'big',
 'booty',
 'bitch',
 'show',
 'him',
 'some',
 'love',
 'http',
 't',
 'co',
 'xddlyR',
 'APq',
 'He',
 's',
 'bitch',
 'keep',
 'looking',
 'at',
 'me',
 'She',
 'choosing',
 'or',
 'nah',
 'RT',
 'Permatrippin',
 'How',
 'i',
 'eat',
 'the',
 'pussy',
 'http',
 't',
 'co',
 'kdFHDx',
 'yDT',
 'jennahnorberg',
 'because',
 'it',
 'retarded',
 'lol',
 'jk',
 'were',
 'the',
 'same',
 'RT',
 'thewayoftheid',
 'Viola',
 'Davis',
 'sans',
 'wig',
 'is',
 'still',
 'stuntin',
 'on',
 'you',
 'hoe',
 'in',
 'the',
 'most',
 'classically',
 'beautiful',
 'way',
 'HTGAWM',
 'I',
 'don',
 't',
 'give',
 'a',
 'fuck',
 'about',
 'yo',
 'gal',
 'yo',
 'wifey',
 'or',
 'yo',
 'boo',
 'came',
 'here',
 'by',
 'myself',
 'bitch',
 'I',
 'm',
 'Tryna',
 'bone',
 'I',
 'm',
 'Camera',
 'Shy',
 'Don',
 't',
 'Talk',
 'on',
 'Phones',
 'and',
 'Love',
 'when',
 'it',
 'rain',
 'If',
 'youn',
 'kno',
 'the',
 'life',
 'you',
 'wouldn',
 't',
 'understand',
 'Lmao',
 'SWILLA_LO',
 'The',
 'd',
 'rose',
 'adidas',
 'are',
 'lighter',
 'than',
 'my',
 'phone',
 'Shit',
 'is',
 'retarded',
 'just',
 'noticed',
 'some',
 'trash',
 'on',
 'my',
 'notification',
 'page',
 'i',
 'had',
 'to',
 'clean',
 'up',
 'How',
 'he',
 'move',
 'in',
 'a',
 'room',
 'full',
 'of',
 'No',
 's',
 'How',
 'he',
 'stay',
 'faithful',
 'in',
 'a',
 'room',
 'full',
 'of',
 'hoe',
 'Beat',
 'the',
 'pussy',
 'in',
 'so',
 'well',
 'her',
 'shit',
 'still',
 'hurting',
 'from',
 'a',
 'week',
 'ago',
 'CSNChicago',
 'Punk',
 'a',
 'bitch',
 'BullsTalk',
 'BlackManUSA',
 'chrislhayes',
 'well',
 'that',
 's',
 'some',
 'cracker',
 'jack',
 'secret',
 'service',
 'work',
 'there',
 'jfk',
 'anyone',
 'Calling',
 'these',
 'nasty',
 'hoe',
 'out',
 'Mrs',
 'Wells',
 'is',
 'too',
 'real',
 'http',
 't',
 'co',
 'D',
 'EnQkDswR',
 'stupid',
 'teacher',
 'talk',
 'to',
 'RandyMower',
 'like',
 'he',
 's',
 'retarded',
 'so',
 'mad',
 'We',
 'live',
 'in',
 'a',
 'world',
 'where',
 'whitey',
 'can',
 'go',
 'to',
 'jail',
 'for',
 'a',
 'word',
 'other',
 'folk',
 'wear',
 'right',
 'on',
 'their',
 'hat',
 'amp',
 'tshirts',
 'If',
 'I',
 'wore',
 'that',
 'shirt',
 'RT',
 'TheHangingWire',
 'don',
 't',
 'EVER',
 'be',
 'ashamed',
 'of',
 'who',
 'you',
 'are',
 'unless',
 'you',
 'a',
 'hoe',
 'then',
 'be',
 'ashamed',
 'bitch',
 'Fuck',
 'a',
 'nigga',
 'feeling',
 'fuck',
 'a',
 'nigga',
 'bitch',
 'RT',
 'mabelsay',
 'Ratchet',
 'bitch',
 'be',
 'like',
 'my',
 'name',
 'is',
 'Shaniqua',
 'assSofatHairSoReal',
 'brown',
 'get',
 'clap',
 'it',
 'clap',
 'right',
 'clap',
 'RT',
 'kiaspeaks',
 'Yall',
 'stay',
 'tracking',
 'pussy',
 'mile',
 'but',
 'refuse',
 'to',
 'put',
 'any',
 'effort',
 'into',
 'controlling',
 'your',
 'own',
 'peen',
 'But',
 'okay',
 'I',
 'guess',
 'Whatever',
 'ke',
 'I',
 'heard',
 'she',
 'pop',
 'pussy',
 'on',
 'the',
 'low',
 'This',
 'bitch',
 'is',
 'earning',
 'figure',
 'for',
 'shaking',
 'a',
 'I',
 'm',
 'so',
 'done',
 'SteveWorks',
 'You',
 'Stockboy',
 'everyone',
 'mock',
 'you',
 'If',
 'you',
 'see',
 'me',
 'SPEAK',
 'bitch',
 'Zack',
 'still',
 'question',
 'my',
 'love',
 'for',
 'Oreos',
 'lol',
 'No',
 'saving',
 'hoe',
 'I',
 'don',
 't',
 'want',
 'a',
 'bitch',
 'that',
 's',
 'erybody',
 'bitch',
 'Lol',
 'at',
 'the',
 'random',
 'fist',
 'fight',
 'aka',
 'pussy',
 'shove',
 'match',
 'at',
 'DnD',
 'tonight',
 'cb_marie',
 'I',
 'need',
 'to',
 'find',
 'is',
 'both',
 'a',
 'damn',
 'job',
 'what_evaittakes',
 'cb_marie',
 'need',
 'to',
 'find',
 'a',
 'bitch',
 'a',
 'job',
 'right',
 'RT',
 'daqraca',
 'How',
 'can',
 'anyone',
 'hate',
 'Charlie',
 'Sheen',
 'http',
 't',
 'co',
 'AF',
 'T',
 'MtmxU',
 'RT',
 'Freegeezy',
 'My',
 'Co',
 'worker',
 'talking',
 'about',
 'what',
 's',
 'my',
 'twitter',
 'name',
 'Oh',
 'no',
 'hoe',
 'you',
 'could',
 'never',
 'screen',
 'shot',
 'me',
 'to',
 'the',
 'bos',
 'garcialaura_',
 'rt',
 'You',
 'll',
 'see',
 'watch',
 'he',
 'finna',
 'hit',
 'that',
 'hoe',
 'and',
 'put',
 'some',
 'RT',
 'DragonBallDeez',
 'Atlanta',
 'RT',
 'PacDaGoat',
 'Houston',
 'ha',
 'so',
 'many',
 'trash',
 'driver',
 'Lmao',
 'if',
 'I',
 'catch',
 'u',
 'in',
 'tha',
 'field',
 'I',
 'm',
 'blowin',
 'Horsepower_Will',
 'PAPER_CHAYSIN',
 'shut',
 'yo',
 'bitch',
 'a',
 'up',
 'opp',
 'lol',
 'coolieDAGGERA',
 'CapoToHeaven',
 'why',
 'wld',
 'u',
 'wan',
 'na',
 'be',
 'a',
 'faggot',
 'dude',
 'That',
 's',
 'faggot',
 'like',
 'Jaime_',
 'Thompson_Era',
 'HannahAlisee',
 'null',
 'bruh',
 'they',
 'both',
 'alive',
 'thats',
 'han',
 'bitch',
 'who',
 'died',
 'Oh',
 'well',
 'FBD',
 'Ima',
 'knock',
 'that',
 'pussy',
 'out',
 'like',
 'fight',
 'http',
 't',
 'co',
 'XvWl',
 'RGD',
 'u',
 'You',
 'just',
 'salty',
 'you',
 'ugly',
 'and',
 'white',
 'RT',
 'JayWiz',
 'ItsNotHarold',
 'they',
 'all',
 'some',
 'hoe',
 'I',
 'really',
 'just',
 'wan',
 'na',
 'brake',
 'your',
 'fucking',
 'head',
 'in',
 'but',
 'I',
 'll',
 'look',
 'like',
 'a',
 'bitch',
 'if',
 'hit',
 'you',
 'RT',
 'VibeLord',
 'I',
 'hate',
 'when',
 'people',
 'think',
 'I',
 'm',
 'mad',
 'or',
 'sad',
 'cause',
 'I',
 'm',
 'not',
 'talking',
 'nah',
 'I',
 'm',
 'chillin',
 'bitch',
 'Willstreakk',
 'Tycff',
 'according',
 'to',
 'you',
 'my',
 'place',
 'is',
 'in',
 'kitchen',
 'Excuse',
 'me',
 'while',
 'I',
 'take',
 'out',
 'the',
 'trash',
 'El_Grillo',
 'Off',
 'to',
 'the',
 'east',
 'of',
 'your',
 'current',
 'location',
 'on',
 'an',
 'east',
 'facing',
 'slope',
 'dry',
 'side',
 'of',
 'a',
 'dry',
 'place',
 'Charles',
 'Tillmans',
 'eye',
 'are',
 'more',
 'yellow',
 'than',
 'corn',
 'RT',
 'RakwonOGOD',
 'Bitches',
 'tweeting',
 'last',
 'night',
 'gt',
 'gt',
 'like',
 'they',
 'did',
 'something',
 'special',
 'except',
 'be',
 'hoe',
 'These',
 'bitch',
 'smell',
 'like',
 'fish',
 'TheCheekyD_',
 'Hi',
 'Yeah',
 'troll',
 'are',
 'annoying',
 'but',
 'don',
 't',
 'concern',
 'yourself',
 'with',
 'them',
 'They',
 're',
 'all',
 'twat',
 ...]

In [107]:
# Creating Vocabulary
from collections import Counter
vocab={'<unk>':0}
for token in Counter(token).keys():
  vocab[token]=len(vocab)

In [47]:
vocab

{'<unk': 0,
 'Drop': 1,
 'it': 2,
 'down': 3,
 'for': 4,
 'a': 5,
 'niggah': 6,
 'socass_': 7,
 'Dude': 8,
 'remember': 9,
 'this': 10,
 'wop': 11,
 'video': 12,
 'sexilexi': 13,
 'http': 14,
 't': 15,
 'co': 16,
 'P': 17,
 'HEuBOQBu': 18,
 'OMG': 19,
 'WHERE': 20,
 'DID': 21,
 'YOU': 22,
 'FIND': 23,
 'THAT': 24,
 'porn': 25,
 'android': 26,
 'iphone': 27,
 'ipad': 28,
 'sex': 29,
 'xxx': 30,
 'Masturbation': 31,
 'A': 32,
 'very': 33,
 'hot': 34,
 'black': 35,
 'tranny': 36,
 'is': 37,
 'mastu': 38,
 'OfGGMLXQAj': 39,
 'RT': 40,
 'tupactopus': 41,
 'need': 42,
 'bad': 43,
 'bitch': 44,
 'who': 45,
 'know': 46,
 'how': 47,
 'treat': 48,
 'pokemon': 49,
 'master': 50,
 'right': 51,
 'Cam_Major': 52,
 'naw': 53,
 'no': 54,
 'b': 55,
 'tho': 56,
 'if': 57,
 'u': 58,
 'under': 59,
 'let': 60,
 'say': 61,
 'and': 62,
 'got': 63,
 'like': 64,
 'body': 65,
 'def': 66,
 'hoe': 67,
 'lol': 68,
 'there': 69,
 'debating': 70,
 'that': 71,
 'Let': 72,
 'me': 73,
 'text': 74,
 'my': 75,
 'gm': 76,
 'or': 77,
 'sumpin': 78,
 'sofancyy_': 79,
 'gone': 80,
 'be': 81,
 'Thad_CastIe': 82,
 'Regrets': 83,
 'are': 84,
 'pussy': 85,
 'Shit': 86,
 'happens': 87,
 'deal': 88,
 'with': 89,
 'BITCH': 90,
 'jla_b': 91,
 'Stop': 92,
 'thinking': 93,
 'ur': 94,
 'entitled': 95,
 'to': 96,
 'politically': 97,
 'correct': 98,
 'response': 99,
 'Black': 100,
 'twitter': 101,
 'get': 102,
 'off': 103,
 'Paul': 104,
 'George': 105,
 'dick': 106,
 'about': 107,
 'him': 108,
 'impregnating': 109,
 'stripper': 110,
 'Wiz': 111,
 'did': 112,
 'Tyga': 113,
 'Kanye': 114,
 'turned': 115,
 'into': 116,
 'housewife': 117,
 'Melo': 118,
 'should': 119,
 've': 120,
 'the': 121,
 'east': 122,
 'now': 123,
 'tweeting': 124,
 'from': 125,
 'tablet': 126,
 'baller': 127,
 'I': 128,
 'didn': 129,
 'forsake': 130,
 'all': 131,
 'other': 132,
 'wife': 133,
 'getting': 134,
 'fucked': 135,
 'on': 136,
 'by': 137,
 'another': 138,
 'nigga': 139,
 'you': 140,
 'she': 141,
 'married': 142,
 'ta': 143,
 'die': 144,
 'verkannt__': 145,
 'what_evaittakes': 146,
 'Nasty': 147,
 'pay': 148,
 'bill': 149,
 'DanWolken': 150,
 'It': 151,
 's': 152,
 'idiotic': 153,
 'opinion': 154,
 'make': 155,
 'poll': 156,
 'less': 157,
 'than': 158,
 'trash': 159,
 'Polls': 160,
 'weren': 161,
 'problem': 162,
 'when': 163,
 'people': 164,
 'integrity': 165,
 'were': 166,
 'voting': 167,
 'Why': 168,
 'would': 169,
 'fuck': 170,
 'can': 171,
 'Jus': 172,
 'don': 173,
 'want': 174,
 'wit': 175,
 'clit': 176,
 'ticckler': 177,
 'lildickytweets': 178,
 'Eugene': 179,
 'come': 180,
 'watch': 181,
 'run': 182,
 'circle': 183,
 'round': 184,
 'rap': 185,
 'game': 186,
 'name': 187,
 'wa': 188,
 'chip': 189,
 'kelly': 190,
 'in': 191,
 'kJzH': 192,
 'U': 193,
 'uSz': 194,
 'h': 195,
 'YessMe_SHAY': 196,
 'pom': 197,
 'back': 198,
 'lmfao': 199,
 'mikecheck_': 200,
 'favorite': 201,
 'drink': 202,
 'of': 203,
 'white': 204,
 'everywhere': 205,
 'JoriBunni': 206,
 'he': 207,
 'talkin': 208,
 'bout': 209,
 'we': 210,
 'wan': 211,
 'na': 212,
 'human': 213,
 'm': 214,
 'just': 215,
 'whet': 216,
 'Tf': 217,
 'acting': 218,
 'sad': 219,
 'Old': 220,
 'Anthony': 221,
 'coming': 222,
 'fashoo': 223,
 'heyrmbr': 224,
 'never': 225,
 'played': 226,
 'Halo': 227,
 'too': 228,
 'busy': 229,
 'slaying': 230,
 'man': 231,
 'weaselfbaby': 232,
 'birthday': 233,
 'All': 234,
 'big': 235,
 'booty': 236,
 'show': 237,
 'some': 238,
 'love': 239,
 'xddlyR': 240,
 'APq': 241,
 'He': 242,
 'keep': 243,
 'looking': 244,
 'at': 245,
 'She': 246,
 'choosing': 247,
 'nah': 248,
 'Permatrippin': 249,
 'How': 250,
 'i': 251,
 'eat': 252,
 'kdFHDx': 253,
 'yDT': 254,
 'jennahnorberg': 255,
 'because': 256,
 'retarded': 257,
 'jk': 258,
 'same': 259,
 'thewayoftheid': 260,
 'Viola': 261,
 'Davis': 262,
 'sans': 263,
 'wig': 264,
 'still': 265,
 'stuntin': 266,
 'most': 267,
 'classically': 268,
 'beautiful': 269,
 'way': 270,
 'HTGAWM': 271,
 'give': 272,
 'yo': 273,
 'gal': 274,
 'wifey': 275,
 'boo': 276,
 'came': 277,
 'here': 278,
 'myself': 279,
 'Tryna': 280,
 'bone': 281,
 'Camera': 282,
 'Shy': 283,
 'Don': 284,
 'Talk': 285,
 'Phones': 286,
 'Love': 287,
 'rain': 288,
 'If': 289,
 'youn': 290,
 'kno': 291,
 'life': 292,
 'wouldn': 293,
 'understand': 294,
 'Lmao': 295,
 'SWILLA_LO': 296,
 'The': 297,
 'd': 298,
 'rose': 299,
 'adidas': 300,
 'lighter': 301,
 'phone': 302,
 'noticed': 303,
 'notification': 304,
 'page': 305,
 'had': 306,
 'clean': 307,
 'up': 308,
 'move': 309,
 'room': 310,
 'full': 311,
 'No': 312,
 'stay': 313,
 'faithful': 314,
 'Beat': 315,
 'so': 316,
 'well': 317,
 'her': 318,
 'shit': 319,
 'hurting': 320,
 'week': 321,
 'ago': 322,
 'CSNChicago': 323,
 'Punk': 324,
 'BullsTalk': 325,
 'BlackManUSA': 326,
 'chrislhayes': 327,
 'cracker': 328,
 'jack': 329,
 'secret': 330,
 'service': 331,
 'work': 332,
 'jfk': 333,
 'anyone': 334,
 'Calling': 335,
 'these': 336,
 'nasty': 337,
 'out': 338,
 'Mrs': 339,
 'Wells': 340,
 'real': 341,
 'D': 342,
 'EnQkDswR': 343,
 'stupid': 344,
 'teacher': 345,
 'talk': 346,
 'RandyMower': 347,
 'mad': 348,
 'We': 349,
 'live': 350,
 'world': 351,
 'where': 352,
 'whitey': 353,
 'go': 354,
 'jail': 355,
 'word': 356,
 'folk': 357,
 'wear': 358,
 'their': 359,
 'hat': 360,
 'amp': 361,
 'tshirts': 362,
 'wore': 363,
 'shirt': 364,
 'TheHangingWire': 365,
 'EVER': 366,
 'ashamed': 367,
 'unless': 368,
 'then': 369,
 'Fuck': 370,
 'feeling': 371,
 'mabelsay': 372,
 'Ratchet': 373,
 'Shaniqua': 374,
 'assSofatHairSoReal': 375,
 'brown': 376,
 'clap': 377,
 'kiaspeaks': 378,
 'Yall': 379,
 'tracking': 380,
 'mile': 381,
 'but': 382,
 'refuse': 383,
 'put': 384,
 'any': 385,
 'effort': 386,
 'controlling': 387,
 'your': 388,
 'own': 389,
 'peen': 390,
 'But': 391,
 'okay': 392,
 'guess': 393,
 'Whatever': 394,
 'ke': 395,
 'heard': 396,
 'pop': 397,
 'low': 398,
 'This': 399,
 'earning': 400,
 'figure': 401,
 'shaking': 402,
 'done': 403,
 'SteveWorks': 404,
 'You': 405,
 'Stockboy': 406,
 'everyone': 407,
 'mock': 408,
 'see': 409,
 'SPEAK': 410,
 'Zack': 411,
 'question': 412,
 'Oreos': 413,
 'saving': 414,
 'erybody': 415,
 'Lol': 416,
 'random': 417,
 'fist': 418,
 'fight': 419,
 'aka': 420,
 'shove': 421,
 'match': 422,
 'DnD': 423,
 'tonight': 424,
 'cb_marie': 425,
 'find': 426,
 'both': 427,
 'damn': 428,
 'job': 429,
 'daqraca': 430,
 'hate': 431,
 'Charlie': 432,
 'Sheen': 433,
 'AF': 434,
 'T': 435,
 'MtmxU': 436,
 'Freegeezy': 437,
 'My': 438,
 'Co': 439,
 'worker': 440,
 'talking': 441,
 'what': 442,
 'Oh': 443,
 'could': 444,
 'screen': 445,
 'shot': 446,
 'bos': 447,
 'garcialaura_': 448,
 'rt': 449,
 'll': 450,
 'finna': 451,
 'hit': 452,
 'DragonBallDeez': 453,
 'Atlanta': 454,
 'PacDaGoat': 455,
 'Houston': 456,
 'ha': 457,
 'many': 458,
 'driver': 459,
 'catch': 460,
 'tha': 461,
 'field': 462,
 'blowin': 463,
 'Horsepower_Will': 464,
 'PAPER_CHAYSIN': 465,
 'shut': 466,
 'opp': 467,
 'coolieDAGGERA': 468,
 'CapoToHeaven': 469,
 'why': 470,
 'wld': 471,
 'faggot': 472,
 'dude': 473,
 'That': 474,
 'Jaime_': 475,
 'Thompson_Era': 476,
 'HannahAlisee': 477,
 'null': 478,
 'bruh': 479,
 'they': 480,
 'alive': 481,
 'thats': 482,
 'han': 483,
 'died': 484,
 'FBD': 485,
 'Ima': 486,
 'knock': 487,
 'XvWl': 488,
 'RGD': 489,
 'salty': 490,
 'ugly': 491,
 'JayWiz': 492,
 'ItsNotHarold': 493,
 'really': 494,
 'brake': 495,
 'fucking': 496,
 'head': 497,
 'look': 498,
 'VibeLord': 499,
 'think': 500,
 'cause': 501,
 'not': 502,
 'chillin': 503,
 'Willstreakk': 504,
 'Tycff': 505,
 'according': 506,
 'place': 507,
 'kitchen': 508,
 'Excuse': 509,
 'while': 510,
 'take': 511,
 'El_Grillo': 512,
 'Off': 513,
 'current': 514,
 'location': 515,
 'an': 516,
 'facing': 517,
 'slope': 518,
 'dry': 519,
 'side': 520,
 'Charles': 521,
 'Tillmans': 522,
 'eye': 523,
 'more': 524,
 'yellow': 525,
 'corn': 526,
 'RakwonOGOD': 527,
 'Bitches': 528,
 'last': 529,
 'night': 530,
 'gt': 531,
 'something': 532,
 'special': 533,
 'except': 534,
 'These': 535,
 'smell': 536,
 'fish': 537,
 'TheCheekyD_': 538,
 'Hi': 539,
 'Yeah': 540,
 'troll': 541,
 'annoying': 542,
 'concern': 543,
 'yourself': 544,
 'them': 545,
 'They': 546,
 're': 547,
 'twat': 548,
 'have': 549,
 'Just': 550,
 'ignore': 551,
 'x': 552,
 'Tattoo_MyLife': 553,
 'cuz': 554,
 'whole': 555,
 'team': 556,
 'Get': 557,
 'Tristine': 558,
 'tried': 559,
 'one': 560,
 'pomegranate': 561,
 'juice': 562,
 'n': 563,
 'swear': 564,
 'tasted': 565,
 'flavored': 566,
 'piss': 567,
 'dont': 568,
 'ask': 569,
 'BitchJones': 570,
 'worshiping': 571,
 'R': 572,
 'CejCjou': 573,
 'woof': 574,
 'RipCaps': 575,
 'Damn': 576,
 'hotter': 577,
 'exactly': 578,
 'dese': 579,
 'doin': 580,
 'Gettin': 581,
 'nd': 582,
 'yall': 583,
 'blame': 584,
 'rebellious_midy': 585,
 'lls': 586,
 'omg': 587,
 'harrassed': 588,
 'bby': 589,
 'father': 590,
 'smh': 591,
 'ig': 592,
 'tlk': 593,
 'hw': 594,
 'mch': 595,
 'miss': 596,
 'please': 597,
 'unfaithful': 598,
 'believe': 599,
 'someone': 600,
 'announced': 601,
 'before': 602,
 'movie': 603,
 'crowd': 604,
 'Lmfao': 605,
 'oh': 606,
 'forgot': 607,
 'texting': 608,
 'DaRealQuitaM': 609,
 'VonshayeB': 610,
 'told': 611,
 'buy': 612,
 'salad': 613,
 'hungry': 614,
 'main': 615,
 'ghost': 616,
 'Pass': 617,
 'stick': 618,
 'gferguson': 619,
 'MSoltan': 620,
 'WBDyllon_': 621,
 'KoredeB': 622,
 'Messi': 623,
 'OprahSideNigga': 624,
 'ToInfinite': 625,
 'exotic': 626,
 'do': 627,
 'thing': 628,
 'aint': 629,
 'loyal': 630,
 'MrRigginss': 631,
 'stfu': 632,
 'strong': 633,
 'asf': 634,
 'ISIS': 635,
 'Jihadis': 636,
 'Discuss': 637,
 'Buying': 638,
 'And': 639,
 'Selling': 640,
 'Yezidi': 641,
 'Girls': 642,
 'As': 643,
 'Slaves': 644,
 'UoPgIPOpWS': 645,
 'tcot': 646,
 'pjnet': 647,
 'This_Sarcasm_': 648,
 'tweet': 649,
 'wasn': 650,
 'shoe': 651,
 'fit': 652,
 'lace': 653,
 'Toxicityy': 654,
 'Gwen': 655,
 'Stefani': 656,
 'new': 657,
 'single': 658,
 'hilary': 659,
 'duff': 660,
 'britney': 661,
 'fergie': 662,
 'raise': 663,
 'kid': 664,
 'judg': 665,
 'CheefPolo': 666,
 'Niggas': 667,
 'time': 668,
 'joke': 669,
 'fam': 670,
 'zero': 671,
 'Most': 672,
 'send': 673,
 'thru': 674,
 'Drunk': 675,
 'inlove': 676,
 'gun': 677,
 'bae': 678,
 'Beyonc': 679,
 'top': 680,
 'notch': 681,
 'lesser': 682,
 'kieffer_jason': 683,
 'said': 684,
 'made': 685,
 'stop': 686,
 'assuming': 687,
 'am': 688,
 'ITS_MAKEPEACE': 689,
 'donno': 690,
 'demz': 691,
 'iz': 692,
 'ima': 693,
 'gurll': 694,
 'ghetto': 695,
 'as': 696,
 'Playing': 697,
 'money': 698,
 'playing': 699,
 'emotion': 700,
 'going': 701,
 'RIPvuhsace': 702,
 'deadass': 703,
 'took': 704,
 'after': 705,
 'ate': 706,
 'darkskin': 707,
 'day': 708,
 'NeverAgain': 709,
 'IZFLyUDuGS': 710,
 '__iamjazz': 711,
 'shaaaaayy_': 712,
 'wish': 713,
 'born': 714,
 'different': 715,
 'generation': 716,
 'hurt': 717,
 'sicken': 718,
 'child': 719,
 'FriendlyAssh': 720,
 'le': 721,
 'tit': 722,
 'even': 723,
 'hug': 724,
 'boy': 725,
 'handshake': 726,
 'LOHANTHONY': 727,
 'private': 728,
 'school': 729,
 'experience': 730,
 'public': 731,
 'brilliant': 732,
 'haha': 733,
 'MHaIphrPbn': 734,
 'Friends': 735,
 'become': 736,
 'foe': 737,
 'girlfriend': 738,
 'circulating': 739,
 'killing': 740,
 'Boko': 741,
 'Haram': 742,
 'Nigerian': 743,
 'pilot': 744,
 'captured': 745,
 'his': 746,
 'helicopter': 747,
 'shoot': 748,
 'Dear': 749,
 'whore': 750,
 'tell': 751,
 'dance': 752,
 'only': 753,
 'dancing': 754,
 'open': 755,
 'leg': 756,
 'shake': 757,
 'ho': 758,
 'shitty': 759,
 'lettherainefall': 760,
 'suck': 761,
 'Do': 762,
 'bird': 763,
 'dong': 764,
 'mate': 765,
 'Help': 766,
 'adult': 767,
 'doesn': 768,
 'animal': 769,
 'st': 770,
 'ayyyeeee': 771,
 'nikkiconner': 772,
 'happy': 773,
 'babbbyyy': 774,
 'ghettobird': 775,
 'er': 776,
 'Yo': 777,
 'givin': 778,
 'Good': 779,
 'Burger': 780,
 'chanelisabeth': 781,
 'Idgaf': 782,
 'flat': 783,
 'chested': 784,
 'either': 785,
 'grown': 786,
 'tabatha__b': 787,
 'Never': 788,
 'worried': 789,
 'next': 790,
 'Always': 791,
 'worryin': 792,
 'meal': 793,
 'tryna': 794,
 'fuckin': 795,
 'great': 796,
 'AmPowerBlog': 797,
 'loser': 798,
 'coward': 799,
 'MikePrysner': 800,
 'grabbed': 801,
 'iPhone': 802,
 'threw': 803,
 'street': 804,
 'CVUbLNgXKj': 805,
 'sayin': 806,
 'baby': 807,
 'already': 808,
 'beigegawdd': 809,
 'Nothing': 810,
 'softer': 811,
 'nigger': 812,
 'BEST': 813,
 'ASIAN': 814,
 'MASSAGE': 815,
 'ON': 816,
 'THE': 817,
 'park': 818,
 'TOP': 819,
 'RATED': 820,
 'SPA': 821,
 'ZsAAzFL': 822,
 'p': 823,
 'phreshagu_': 824,
 'yeah': 825,
 'Mexicans': 826,
 'bringing': 827,
 'family': 828,
 'packed': 829,
 'JuanNDaCut': 830,
 'When': 831,
 'rapper': 832,
 'dm': 833,
 'link': 834,
 'yck': 835,
 'ZiNZZ': 836,
 'MarsDaBlackman': 837,
 'relate': 838,
 'being': 839,
 'lonely': 840,
 'depressed': 841,
 'Been': 842,
 'sleeping': 843,
 'toooooo': 844,
 'much': 845,
 'enjoy': 846,
 'start': 847,
 'working': 848,
 'versacecum': 849,
 'everybody': 850,
 'business': 851,
 'TrayvonMartin': 852,
 'referred': 853,
 'Zimmerman': 854,
 'creepy': 855,
 'Racist': 856,
 'thug': 857,
 'Prinncesskimm_': 858,
 'attractive': 859,
 'After': 860,
 'Deztinis': 861,
 'session': 862,
 'needed': 863,
 'lmao': 864,
 'Jk': 865,
 'girl': 866,
 'good': 867,
 'yob': 868,
 'spfhBBkVD': 869,
 'Chokmah_Makob': 870,
 'ok': 871,
 'billy': 872,
 'goat': 873,
 'hair': 874,
 'hillbilly': 875,
 'TrentSkii_Baby': 876,
 '_Sqquad': 877,
 'Fucking': 878,
 'use': 879,
 'BkBap': 880,
 'seat': 881,
 'also': 882,
 'assume': 883,
 'woman': 884,
 'contributes': 885,
 'convo': 886,
 'mean': 887,
 'f': 888,
 'label': 889,
 'nano': 890,
 'lt': 891,
 'StephyRae': 892,
 'Trainer': 893,
 'lady': 894,
 'shook': 895,
 'hand': 896,
 'promise': 897,
 'ma': 898,
 'study': 899,
 'test': 900,
 'tomorrow': 901,
 'idk': 902,
 'trying': 903,
 'break': 904,
 'PapaRockk_': 905,
 'mom': 906,
 'paid': 907,
 'hold': 908,
 'monkey': 909,
 'ZkMd': 910,
 'Xeh': 911,
 'sister': 912,
 'walk': 913,
 'blade': 914,
 'EVERYNIGHT': 915,
 'NO': 916,
 'PLACE': 917,
 'try': 918,
 'wtf': 919,
 'shouldnt': 920,
 'monique': 921,
 'Q': 922,
 'ByeKandace': 923,
 'hop': 924,
 'KekePalmer': 925,
 'Come': 926,
 'KSTiLLS': 927,
 'donnyoraha': 928,
 'Dont': 929,
 'Stfu_NobodyCare': 930,
 'codizzlleee': 931,
 'Satisfied_x': 932,
 'fck': 933,
 'thank': 934,
 'classy': 935,
 'dead': 936,
 'JawShoeeAhhh': 937,
 'summerdawn_': 938,
 'NudesAreMyLife': 939,
 'omfg': 940,
 'mine': 941,
 'TrueNovacane': 942,
 'UFUCKIN_RIGHT': 943,
 'hell': 944,
 'nahh': 945,
 'respect': 946,
 'tkPokv': 947,
 'ncd': 948,
 'Jets': 949,
 'roLLYuP': 950,
 'Who': 951,
 'wrestling': 952,
 'besides': 953,
 'little': 954,
 'K': 955,
 'follower': 956,
 'drive': 957,
 'honda': 958,
 'bender': 959,
 'flappy': 960,
 'again': 961,
 'ever': 962,
 'CayMarieee': 963,
 'couldn': 964,
 'answer': 965,
 'paccage': 966,
 'delivered': 967,
 'house': 968,
 'So': 969,
 'Fucc': 970,
 'might': 971,
 'Dats': 972,
 'feel': 973,
 'oodbPTGV': 974,
 'icpchad': 975,
 'UnseeingEyes': 976,
 'AriaunaDaVon': 977,
 'Did': 978,
 'cry': 979,
 'AndyMilonakis': 980,
 'Amex': 981,
 'once': 982,
 'gon': 983,
 'act': 984,
 'chilly': 985,
 'snob': 986,
 'cardigan': 987,
 'karate': 988,
 'SirAsshole': 989,
 'Karrenchi': 990,
 'mouth': 991,
 'davis_lyndsi': 992,
 'blocked': 993,
 '_viktoriagracee': 994,
 'bake': 995,
 'cooky': 996,
 'forever': 997,
 'Is': 998,
 'remix': 999,
 ...}

In [49]:
# Tokenize Sentence

tokenize_sentence = [
    word_tokenize(str(sentence))
    for sentence in sub_df['final_tweets']
]

In [50]:
tokenize_sentence

[['Drop', 'it', 'down', 'for', 'a', 'niggah'],
 ['socass_',
  'Dude',
  'remember',
  'this',
  'wop',
  'video',
  'sexilexi',
  'http',
  't',
  'co',
  'P',
  'HEuBOQBu',
  'OMG',
  'WHERE',
  'DID',
  'YOU',
  'FIND',
  'THAT'],
 ['porn',
  'android',
  'iphone',
  'ipad',
  'sex',
  'xxx',
  'Masturbation',
  'A',
  'very',
  'hot',
  'black',
  'tranny',
  'is',
  'mastu',
  'http',
  't',
  'co',
  'OfGGMLXQAj'],
 ['RT',
  'tupactopus',
  'need',
  'a',
  'bad',
  'bitch',
  'who',
  'know',
  'how',
  'treat',
  'a',
  'pokemon',
  'master',
  'right'],
 ['RT',
  'Cam_Major',
  'naw',
  'no',
  'b',
  'tho',
  'if',
  'u',
  'under',
  'let',
  'say',
  'and',
  'u',
  'got',
  'like',
  'body',
  'u',
  'def',
  'a',
  'hoe',
  'lol',
  'there',
  'no',
  'debating',
  'that'],
 ['Let', 'me', 'text', 'my', 'hoe', 'gm', 'or', 'sumpin'],
 ['RT', 'sofancyy_', 'A', 'hoe', 'gone', 'be', 'a', 'hoe'],
 ['RT',
  'Thad_CastIe',
  'Regrets',
  'are',
  'for',
  'pussy',
  'Shit',
  'happens',
  'deal',
  'with',
  'it'],
 ['BITCH',
  'RT',
  'jla_b',
  'Stop',
  'thinking',
  'ur',
  'entitled',
  'to',
  'politically',
  'correct',
  'response',
  'bitch'],
 ['Black',
  'twitter',
  'need',
  'to',
  'get',
  'off',
  'Paul',
  'George',
  'dick',
  'about',
  'him',
  'impregnating',
  'a',
  'stripper',
  'Wiz',
  'did',
  'Tyga',
  'did',
  'Kanye',
  'turned',
  'a',
  'hoe',
  'into',
  'a',
  'housewife'],
 ['Melo', 'should', 've', 'got', 'the', 'bitch', 'for', 'the', 'east'],
 ['is', 'now', 'tweeting', 'from', 'a', 'tablet', 'baller', 'bitch'],
 ['I',
  'didn',
  't',
  'forsake',
  'all',
  'other',
  'bitch',
  'for',
  'my',
  'wife',
  'to',
  'be',
  'getting',
  'fucked',
  'on',
  'by',
  'another',
  'nigga',
  'and',
  'you',
  'know',
  'she',
  'married',
  'you',
  'got',
  'ta',
  'die'],
 ['verkannt__', 'what_evaittakes', 'Nasty', 'pay', 'the', 'bill', 'bitch'],
 ['DanWolken',
  'It',
  's',
  'idiotic',
  'opinion',
  'like',
  'this',
  'that',
  'make',
  'poll',
  'less',
  'than',
  'trash',
  'Polls',
  'weren',
  't',
  'a',
  'problem',
  'when',
  'people',
  'with',
  'integrity',
  'were',
  'voting'],
 ['Why',
  'would',
  'I',
  'fuck',
  'a',
  'bitch',
  'that',
  'can',
  't',
  'fuck',
  'Jus',
  'like',
  'u',
  'hoe',
  'don',
  't',
  'want',
  'want',
  'a',
  'nigga',
  'wit',
  'a',
  'clit',
  'ticckler'],
 ['RT',
  'lildickytweets',
  'Eugene',
  'come',
  'watch',
  'me',
  'run',
  'circle',
  'round',
  'the',
  'rap',
  'game',
  'like',
  'my',
  'name',
  'wa',
  'chip',
  'kelly',
  'in',
  'this',
  'bitch',
  'http',
  't',
  'co',
  'kJzH',
  'U',
  'uSz',
  'h'],
 ['YessMe_SHAY', 'I', 'want', 'my', 'pom', 'back', 'lmfao'],
 ['mikecheck_',
  'the',
  'favorite',
  'drink',
  'of',
  'white',
  'trash',
  'everywhere'],
 ['JoriBunni',
  'he',
  'talkin',
  'bout',
  'we',
  'wan',
  'na',
  'be',
  'human',
  'and',
  'I',
  'm',
  'just',
  'like',
  'bitch',
  'whet'],
 ['Tf',
  'I',
  'm',
  'acting',
  'like',
  'a',
  'sad',
  'a',
  'bitch',
  'for',
  'Old',
  'Anthony',
  'coming',
  'back',
  'fashoo'],
 ['heyrmbr',
  'I',
  'never',
  'played',
  'Halo',
  'too',
  'busy',
  'slaying',
  'bitch'],
 ['It',
  's',
  'my',
  'man',
  'weaselfbaby',
  'birthday',
  'All',
  'the',
  'big',
  'booty',
  'bitch',
  'show',
  'him',
  'some',
  'love',
  'http',
  't',
  'co',
  'xddlyR',
  'APq'],
 ['He',
  's',
  'bitch',
  'keep',
  'looking',
  'at',
  'me',
  'She',
  'choosing',
  'or',
  'nah'],
 ['RT',
  'Permatrippin',
  'How',
  'i',
  'eat',
  'the',
  'pussy',
  'http',
  't',
  'co',
  'kdFHDx',
  'yDT'],
 ['jennahnorberg',
  'because',
  'it',
  'retarded',
  'lol',
  'jk',
  'were',
  'the',
  'same'],
 ['RT',
  'thewayoftheid',
  'Viola',
  'Davis',
  'sans',
  'wig',
  'is',
  'still',
  'stuntin',
  'on',
  'you',
  'hoe',
  'in',
  'the',
  'most',
  'classically',
  'beautiful',
  'way',
  'HTGAWM'],
 ['I',
  'don',
  't',
  'give',
  'a',
  'fuck',
  'about',
  'yo',
  'gal',
  'yo',
  'wifey',
  'or',
  'yo',
  'boo',
  'came',
  'here',
  'by',
  'myself',
  'bitch',
  'I',
  'm',
  'Tryna',
  'bone'],
 ['I',
  'm',
  'Camera',
  'Shy',
  'Don',
  't',
  'Talk',
  'on',
  'Phones',
  'and',
  'Love',
  'when',
  'it',
  'rain',
  'If',
  'youn',
  'kno',
  'the',
  'life',
  'you',
  'wouldn',
  't',
  'understand'],
 ['Lmao',
  'SWILLA_LO',
  'The',
  'd',
  'rose',
  'adidas',
  'are',
  'lighter',
  'than',
  'my',
  'phone',
  'Shit',
  'is',
  'retarded'],
 ['just',
  'noticed',
  'some',
  'trash',
  'on',
  'my',
  'notification',
  'page',
  'i',
  'had',
  'to',
  'clean',
  'up'],
 ['How',
  'he',
  'move',
  'in',
  'a',
  'room',
  'full',
  'of',
  'No',
  's',
  'How',
  'he',
  'stay',
  'faithful',
  'in',
  'a',
  'room',
  'full',
  'of',
  'hoe'],
 ['Beat',
  'the',
  'pussy',
  'in',
  'so',
  'well',
  'her',
  'shit',
  'still',
  'hurting',
  'from',
  'a',
  'week',
  'ago'],
 ['CSNChicago', 'Punk', 'a', 'bitch', 'BullsTalk'],
 ['BlackManUSA',
  'chrislhayes',
  'well',
  'that',
  's',
  'some',
  'cracker',
  'jack',
  'secret',
  'service',
  'work',
  'there',
  'jfk',
  'anyone'],
 ['Calling',
  'these',
  'nasty',
  'hoe',
  'out',
  'Mrs',
  'Wells',
  'is',
  'too',
  'real',
  'http',
  't',
  'co',
  'D',
  'EnQkDswR'],
 ['stupid',
  'teacher',
  'talk',
  'to',
  'RandyMower',
  'like',
  'he',
  's',
  'retarded'],
 ['so',
  'mad',
  'We',
  'live',
  'in',
  'a',
  'world',
  'where',
  'whitey',
  'can',
  'go',
  'to',
  'jail',
  'for',
  'a',
  'word',
  'other',
  'folk',
  'wear',
  'right',
  'on',
  'their',
  'hat',
  'amp',
  'tshirts',
  'If',
  'I',
  'wore',
  'that',
  'shirt'],
 ['RT',
  'TheHangingWire',
  'don',
  't',
  'EVER',
  'be',
  'ashamed',
  'of',
  'who',
  'you',
  'are',
  'unless',
  'you',
  'a',
  'hoe',
  'then',
  'be',
  'ashamed',
  'bitch'],
 ['Fuck', 'a', 'nigga', 'feeling', 'fuck', 'a', 'nigga', 'bitch'],
 ['RT',
  'mabelsay',
  'Ratchet',
  'bitch',
  'be',
  'like',
  'my',
  'name',
  'is',
  'Shaniqua',
  'assSofatHairSoReal',
  'brown',
  'get',
  'clap',
  'it',
  'clap',
  'right',
  'clap'],
 ['RT',
  'kiaspeaks',
  'Yall',
  'stay',
  'tracking',
  'pussy',
  'mile',
  'but',
  'refuse',
  'to',
  'put',
  'any',
  'effort',
  'into',
  'controlling',
  'your',
  'own',
  'peen',
  'But',
  'okay',
  'I',
  'guess',
  'Whatever',
  'ke'],
 ['I', 'heard', 'she', 'pop', 'pussy', 'on', 'the', 'low'],
 ['This',
  'bitch',
  'is',
  'earning',
  'figure',
  'for',
  'shaking',
  'a',
  'I',
  'm',
  'so',
  'done'],
 ['SteveWorks', 'You', 'Stockboy', 'everyone', 'mock', 'you'],
 ['If', 'you', 'see', 'me', 'SPEAK', 'bitch'],
 ['Zack', 'still', 'question', 'my', 'love', 'for', 'Oreos', 'lol'],
 ['No', 'saving', 'hoe'],
 ['I', 'don', 't', 'want', 'a', 'bitch', 'that', 's', 'erybody', 'bitch'],
 ['Lol',
  'at',
  'the',
  'random',
  'fist',
  'fight',
  'aka',
  'pussy',
  'shove',
  'match',
  'at',
  'DnD',
  'tonight'],
 ['cb_marie',
  'I',
  'need',
  'to',
  'find',
  'is',
  'both',
  'a',
  'damn',
  'job',
  'what_evaittakes',
  'cb_marie',
  'need',
  'to',
  'find',
  'a',
  'bitch',
  'a',
  'job',
  'right'],
 ['RT',
  'daqraca',
  'How',
  'can',
  'anyone',
  'hate',
  'Charlie',
  'Sheen',
  'http',
  't',
  'co',
  'AF',
  'T',
  'MtmxU'],
 ['RT',
  'Freegeezy',
  'My',
  'Co',
  'worker',
  'talking',
  'about',
  'what',
  's',
  'my',
  'twitter',
  'name',
  'Oh',
  'no',
  'hoe',
  'you',
  'could',
  'never',
  'screen',
  'shot',
  'me',
  'to',
  'the',
  'bos'],
 ['garcialaura_',
  'rt',
  'You',
  'll',
  'see',
  'watch',
  'he',
  'finna',
  'hit',
  'that',
  'hoe',
  'and',
  'put',
  'some'],
 ['RT',
  'DragonBallDeez',
  'Atlanta',
  'RT',
  'PacDaGoat',
  'Houston',
  'ha',
  'so',
  'many',
  'trash',
  'driver'],
 ['Lmao',
  'if',
  'I',
  'catch',
  'u',
  'in',
  'tha',
  'field',
  'I',
  'm',
  'blowin',
  'Horsepower_Will',
  'PAPER_CHAYSIN',
  'shut',
  'yo',
  'bitch',
  'a',
  'up',
  'opp',
  'lol'],
 ['coolieDAGGERA',
  'CapoToHeaven',
  'why',
  'wld',
  'u',
  'wan',
  'na',
  'be',
  'a',
  'faggot',
  'dude',
  'That',
  's',
  'faggot',
  'like'],
 ['Jaime_',
  'Thompson_Era',
  'HannahAlisee',
  'null',
  'bruh',
  'they',
  'both',
  'alive',
  'thats',
  'han',
  'bitch',
  'who',
  'died',
  'Oh',
  'well',
  'FBD'],
 ['Ima',
  'knock',
  'that',
  'pussy',
  'out',
  'like',
  'fight',
  'http',
  't',
  'co',
  'XvWl',
  'RGD',
  'u'],
 ['You',
  'just',
  'salty',
  'you',
  'ugly',
  'and',
  'white',
  'RT',
  'JayWiz',
  'ItsNotHarold',
  'they',
  'all',
  'some',
  'hoe'],
 ['I',
  'really',
  'just',
  'wan',
  'na',
  'brake',
  'your',
  'fucking',
  'head',
  'in',
  'but',
  'I',
  'll',
  'look',
  'like',
  'a',
  'bitch',
  'if',
  'hit',
  'you'],
 ['RT',
  'VibeLord',
  'I',
  'hate',
  'when',
  'people',
  'think',
  'I',
  'm',
  'mad',
  'or',
  'sad',
  'cause',
  'I',
  'm',
  'not',
  'talking',
  'nah',
  'I',
  'm',
  'chillin',
  'bitch'],
 ['Willstreakk',
  'Tycff',
  'according',
  'to',
  'you',
  'my',
  'place',
  'is',
  'in',
  'kitchen',
  'Excuse',
  'me',
  'while',
  'I',
  'take',
  'out',
  'the',
  'trash'],
 ['El_Grillo',
  'Off',
  'to',
  'the',
  'east',
  'of',
  'your',
  'current',
  'location',
  'on',
  'an',
  'east',
  'facing',
  'slope',
  'dry',
  'side',
  'of',
  'a',
  'dry',
  'place'],
 ['Charles', 'Tillmans', 'eye', 'are', 'more', 'yellow', 'than', 'corn'],
 ['RT',
  'RakwonOGOD',
  'Bitches',
  'tweeting',
  'last',
  'night',
  'gt',
  'gt',
  'like',
  'they',
  'did',
  'something',
  'special',
  'except',
  'be',
  'hoe'],
 ['These', 'bitch', 'smell', 'like', 'fish'],
 ['TheCheekyD_',
  'Hi',
  'Yeah',
  'troll',
  'are',
  'annoying',
  'but',
  'don',
  't',
  'concern',
  'yourself',
  'with',
  'them',
  'They',
  're',
  'all',
  'twat',
  'amp',
  'have',
  'no',
  'life',
  'lol',
  'Just',
  'ignore',
  'them',
  'x'],
 ['Tattoo_MyLife', 'cuz', 'the', 'whole', 'team', 'trash'],
 ['Get', 'on', 'your', 'shit', 'hoe'],
 ['Tristine',
  'I',
  'tried',
  'one',
  'of',
  'them',
  'pom',
  'pomegranate',
  'juice',
  'n',
  'I',
  'swear',
  'it',
  'tasted',
  'like',
  'flavored',
  'piss',
  'dont',
  'ask',
  'lol'],
 ['BitchJones',
  'Get',
  'worshiping',
  'bitch',
  'http',
  't',
  'co',
  'R',
  'CejCjou',
  'woof',
  'woof'],
 ['RT', 'RipCaps', 'Damn', 'it', 's', 'hotter', 'than', 'a', 'bitch'],
 ['Fuck',
  'that',
  'hoe',
  'thats',
  'exactly',
  'what',
  'dese',
  'hoe',
  'doin',
  'Gettin',
  'fucked',
  'nd',
  'yall',
  'nigga',
  'the',
  'one',
  'to',
  'blame'],
 ['rebellious_midy',
  'lls',
  'omg',
  'omg',
  'me',
  'too',
  'getting',
  'harrassed',
  'by',
  'my',
  'bby',
  'father',
  'smh',
  'on',
  'ig',
  'tlk',
  'bout',
  'hw',
  'mch',
  'he',
  'miss',
  'me',
  'bitch',
  'please'],
 ['lol', 'unfaithful', 'hoe'],
 ['I',
  'can',
  't',
  'believe',
  'that',
  'someone',
  'announced',
  'before',
  'the',
  'movie',
  'to',
  'the',
  'crowd',
  'that',
  'They',
  'came',
  'for',
  'the',
  'bitch'],
 ['Lmfao',
  'oh',
  'i',
  'forgot',
  'texting',
  'it',
  'to',
  'u',
  'now',
  'RT',
  'DaRealQuitaM',
  'VonshayeB',
  'I',
  'told',
  'u',
  'to',
  'text',
  'me',
  'what',
  'I',
  'need',
  'to',
  'buy',
  'for',
  'the',
  'salad',
  'a',
  'bitch',
  'hungry'],
 ['My', 'main', 'bitch', 'is', 'a', 'ghost'],
 ['Pass', 'them', 'stick', 'bitch'],
 ['RT',
  'gferguson',
  'MSoltan',
  'WBDyllon_',
  'KoredeB',
  'Messi',
  'is',
  'trash'],
 ['OprahSideNigga',
  'ToInfinite',
  'exotic',
  'bitch',
  'do',
  'exotic',
  'thing',
  'these',
  'hoe',
  'aint',
  'loyal'],
 ['RT', 'MrRigginss', 'my', 'bitch', 'stfu', 'game', 'strong', 'asf'],
 ['ISIS',
  'Jihadis',
  'Discuss',
  'Buying',
  'And',
  'Selling',
  'Yezidi',
  'Girls',
  'As',
  'Slaves',
  'http',
  't',
  'co',
  'UoPgIPOpWS',
  'tcot',
  'pjnet'],
 ['RT',
  'This_Sarcasm_',
  'my',
  'tweet',
  'wasn',
  't',
  'really',
  'about',
  'you',
  'but',
  'if',
  'the',
  'shoe',
  'fit',
  'then',
  'lace',
  'that',
  'bitch',
  'up',
  'and',
  'wear',
  'it'],
 ['RT',
  'Toxicityy',
  'Gwen',
  'Stefani',
  's',
  'new',
  'single',
  'is',
  'trash',
  'her',
  'hilary',
  'duff',
  'britney',
  'and',
  'fergie',
  'have',
  'to',
  'give',
  'it',
  'up',
  'and',
  'go',
  'raise',
  'your',
  'kid',
  'and',
  'judg'],
 ['RT',
  'CheefPolo',
  'Niggas',
  'be',
  'like',
  'I',
  'get',
  'time',
  'the',
  'pussy',
  'you',
  'get',
  'joke',
  'on',
  'you',
  'fam',
  'time',
  'is',
  'zero'],
 ['Most', 'nigga', 'send', 'hate', 'thru', 'the', 'bitch'],
 ['Drunk', 'inlove', 'with', 'my', 'gun', 'bae', 'bitch', 'Beyonc'],
 ['top', 'notch', 'hoe', 'get', 'the', 'most', 'not', 'the', 'lesser'],
 ['kieffer_jason',
  'and',
  'who',
  'said',
  'I',
  'didn',
  't',
  'like',
  'myself',
  'where',
  'the',
  'fuck',
  'u',
  'got',
  'shit',
  'from',
  'u',
  'made',
  'that',
  'up',
  'stfu',
  'and',
  'stop',
  'assuming',
  'and',
  'bitch',
  'am',
  'not',
  'ugly'],
 ['ITS_MAKEPEACE',
  'i',
  'donno',
  'who',
  'demz',
  'iz',
  'But',
  'ima',
  'bout',
  'to',
  'get',
  'white',
  'gurll',
  'ghetto',
  'on',
  'there',
  'as',
  'when',
  'i',
  'find',
  'out'],
 ['Playing',
  'with',
  'my',
  'money',
  'is',
  'like',
  'playing',
  'with',
  'my',
  'emotion',
  'nigga',
  'don',
  't',
  'believe',
  'I',
  'guess',
  'we',
  'going',
  'to',
  'find',
  'out',
  'then',
  'hoe',
  'a',
  'nigga'],
 ['RT',
  'RIPvuhsace',
  'I',
  'deadass',
  'took',
  'this',
  'after',
  'i',
  'ate',
  'a',
  'darkskin',
  'bitch',
  'pussy',
  'the',
  'other',
  'day',
  'NeverAgain',
  'http',
  't',
  'co',
  'IZFLyUDuGS'],
 ['RT',
  '__iamjazz',
  'shaaaaayy_',
  'i',
  'wish',
  'i',
  'wa',
  'born',
  'in',
  'a',
  'different',
  'generation',
  'cause',
  'yall',
  'just',
  'make',
  'my',
  'pussy',
  'bone',
  'hurt',
  'sicken',
  'a',
  'child'],
 ['RT',
  'FriendlyAssh',
  'le',
  'bitch',
  'with',
  'no',
  'tit',
  'or',
  'a',
  'dont',
  'even',
  'get',
  'a',
  'hug',
  'from',
  'me',
  'you',
  're',
  'one',
  'of',
  'the',
  'boy',
  'now',
  'you',
  'get',
  'a',
  'handshake'],
 ['RT',
  'LOHANTHONY',
  'i',
  'd',
  'never',
  'send',
  'my',
  'kid',
  'to',
  'private',
  'school',
  'because',
  'then',
  'they',
  'would',
  'never',
  'experience',
  'ghetto',
  'public',
  'school',
  'fight'],
 ['bitch', 'be', 'brilliant', 'haha', 'http', 't', 'co', 'MHaIphrPbn'],
 ['Friends', 'become', 'foe', 'girlfriend', 'become', 'hoe'],
 ['Jihadis',
  'circulating',
  'a',
  'video',
  'of',
  'the',
  'killing',
  'by',
  'Boko',
  'Haram',
  'of',
  'a',
  'Nigerian',
  'pilot',
  'captured',
  'after',
  'his',
  'helicopter',
  'wa',
  'shoot',
  'down'],
 ['Dear',
  'whore',
  'Don',
  't',
  'tell',
  'me',
  'I',
  'can',
  't',
  'dance',
  'when',
  'the',
  'only',
  'dancing',
  'you',
  'do',
  'is',
  'open',
  'your',
  'leg',
  'and',
  'shake',
  'your',
  'a',
  'like',
  'a',
  'video',
  'ho',
  'to',
  'shitty',
  'rap'],
 ['lettherainefall', 'suck', 'to', 'suck', 'bitch'],
 ['Do',
  'bird',
  'have',
  'dong',
  'How',
  'do',
  'they',
  'mate',
  'Help',
  'me',
  'I',
  'm',
  'an',
  'adult',
  'who',
  'doesn',
  't',
  'know',
  'how',
  'animal',
  'sex',
  'work'],
 ['It',
  's',
  'my',
  'main',
  'bitch',
  'st',
  'ayyyeeee',
  'nikkiconner',
  'happy',
  'birthday',
  'babbbyyy'],
 ['RT',
  'ghettobird',
  'er',
  'Yo',
  'bitch',
  'givin',
  'me',
  'head',
  'while',
  'I',
  'watch',
  'Good',
  'Burger'],
 ['chanelisabeth', 'fuck', 'yo', 'bitch', 'a', 'then'],
 ['Idgaf',
  'about',
  'you',
  'flat',
  'chested',
  'hoe',
  'feeling',
  'either',
  'you',
  'a',
  'grown',
  'a',
  'man',
  'nigga'],
 ['tabatha__b',
  'Never',
  'worried',
  'about',
  'the',
  'next',
  'bitch',
  'Always',
  'worryin',
  'about',
  'the',
  'next',
  'meal',
  'I',
  'm',
  'tryna',
  'fuckin',
  'eat',
  'fuck',
  'what',
  'you',
  'talkin',
  'bout'],
 ['This',
  'is',
  'great',
  'RT',
  'AmPowerBlog',
  'loser',
  'amp',
  'coward',
  'MikePrysner',
  'grabbed',
  'my',
  'iPhone',
  'and',
  'threw',
  'it',
  'in',
  'the',
  'street',
  'He',
  's',
  'a',
  'pussy',
  'http',
  't',
  'co',
  'CVUbLNgXKj'],
 ['I',
  'm',
  'just',
  'sayin',
  'That',
  's',
  'my',
  'baby',
  'amp',
  'I',
  'already',
  'told',
  'you',
  'bitch'],
 ['OMG',
  'RT',
  'beigegawdd',
  'Nothing',
  'in',
  'life',
  'ha',
  'made',
  'me',
  'softer',
  'than',
  'Fuck',
  'me',
  'with',
  'your',
  'nigger',
  'dick'],
 ['BEST',
  'ASIAN',
  'MASSAGE',
  'ON',
  'THE',
  'park',
  'slope',
  'TOP',
  'RATED',
  'SPA',
  'http',
  't',
  'co',
  'ZsAAzFL',
  'p'],
 ['phreshagu_',
  'yeah',
  'you',
  'right',
  'and',
  'you',
  'know',
  'them',
  'Mexicans',
  'bringing',
  'all',
  'they',
  'family',
  'that',
  'hoe',
  'finna',
  'be',
  'packed'],
 ['RT',
  'JuanNDaCut',
  'When',
  'twitter',
  'rapper',
  'dm',
  'me',
  'their',
  'trash',
  'link',
  'http',
  't',
  'co',
  'yck',
  'ZiNZZ'],
 ['MarsDaBlackman',
  'thats',
  'why',
  'the',
  'hoe',
  'love',
  'her',
  'they',
  'can',
  'relate',
  'to',
  'being',
  'lonely',
  'amp',
  'depressed',
  'lol'],
 ['Been',
  'sleeping',
  'toooooo',
  'much',
  'fuck',
  'it',
  'ima',
  'enjoy',
  'it',
  'before',
  'i',
  'start',
  'working',
  'job',
  'like',
  'a',
  'hoe',
  'haha'],
 ['RT',
  'versacecum',
  'bitch',
  'be',
  'like',
  'but',
  'still',
  'be',
  'in',
  'everybody',
  's',
  'business'],
 ['TrayvonMartin',
  'referred',
  'to',
  'Zimmerman',
  'a',
  'a',
  'creepy',
  'a',
  'cracker',
  'Racist',
  'thug'],
 ['RT', 'Prinncesskimm_', 'All', 'my', 'bitch', 'attractive'],
 ['After',
  'Deztinis',
  'session',
  'we',
  'needed',
  'this',
  'lmao',
  'Jk',
  'girl',
  'good',
  'yob',
  'lol',
  'http',
  't',
  'co',
  'spfhBBkVD'],
 ['Chokmah_Makob', 'ok', 'you', 'billy', 'goat', 'hair', 'hillbilly'],
 ['RT',
  'TrentSkii_Baby',
  '_Sqquad',
  'Fucking',
  'nigga',
  'bitch',
  'man',
  'I',
  'm',
  'use',
  'to',
  'it'],
 ['RT',
  'BkBap',
  'like',
  'to',
  'have',
  'a',
  'seat',
  'on',
  'it',
  'I',
  'also',
  'don',
  't',
  'assume',
  'that',
  'because',
  'a',
  'woman',
  'contributes',
  'to',
  'a',
  'sex',
  'convo',
  'that',
  'mean',
  'her',
  'pussy',
  'is',
  'open',
  'f'],
 ['When',
  'people',
  'label',
  'their',
  'name',
  'on',
  'there',
  'ghetto',
  'nano',
  'lt',
  'lt',
  'lt',
  'lt',
  'lt',
  'StephyRae'],
 ['Trainer',
  'lady',
  'is',
  'a',
  'bitch',
  'shook',
  'my',
  'hand',
  'made',
  'me',
  'promise',
  'her',
  'I',
  'ma',
  'study',
  'for',
  'a',
  'test',
  'tomorrow',
  'and',
  'idk',
  'I',
  'don',
  't',
  'like',
  'her',
  'she',
  's',
  'trying',
  'to',
  'break',
  'me'],
 ['RT',
  'PapaRockk_',
  'My',
  'mom',
  'paid',
  'to',
  'hold',
  'this',
  'monkey',
  'amp',
  'look',
  'what',
  'he',
  'did',
  'http',
  't',
  'co',
  't',
  'ZkMd',
  'Xeh'],
 ['My',
  'sister',
  'use',
  'to',
  'walk',
  'the',
  'blade',
  'EVERYNIGHT',
  'so',
  'the',
  'way',
  'I',
  'see',
  'it',
  'that',
  'bitch',
  'don',
  't',
  'have',
  'NO',
  'PLACE',
  'to',
  'try',
  'amp',
  'tell',
  'me',
  'wtf',
  'I',
  'should',
  'amp',
  'shouldnt',
  'do'],
 ['RT',
  'monique',
  'Q',
  'ByeKandace',
  'hop',
  'off',
  'hoe',
  'RT',
  'KekePalmer',
  'Come',
  'on',
  'KSTiLLS'],
 ['RT', 'donnyoraha', 'Dont', 'fuck', 'with', 'u', 'hoe'],
 ['Stfu_NobodyCare',
  'codizzlleee',
  'Satisfied_x',
  'you',
  'fck',
  'like',
  'a',
  'hoe',
  'so',
  'no',
  'thank',
  'you',
  'Ima',
  'be',
  'classy',
  'when',
  'I',
  'do',
  'it',
  'bitch',
  'I',
  'm',
  'dead'],
 ['JawShoeeAhhh', 'shut', 'up', 'bitch'],
 ['summerdawn_', 'NudesAreMyLife', 'omfg', 'that', 's', 'mine', 'faggot'],
 ['RT',

In [52]:
def text_to_indices(sentence,vocab):
  numeric_sentence=[]
  for token in sentence:
    if token not in vocab:
      numeric_sentence.append(vocab['<unk>'])
    else:
      numeric_sentence.append(vocab[token])
  return numeric_sentence

In [54]:
input_numeric_sentence=[]
for sentence in tokenize_sentence:
  input_numeric_sentence.append(text_to_indices(sentence,vocab))

In [55]:
input_numeric_sentence

[[1, 2, 3, 4, 5, 6],
 [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
 [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 14, 15, 16, 39],
 [40, 41, 42, 5, 43, 44, 45, 46, 47, 48, 5, 49, 50, 51],
 [40,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  58,
  63,
  64,
  65,
  58,
  66,
  5,
  67,
  68,
  69,
  54,
  70,
  71],
 [72, 73, 74, 75, 67, 76, 77, 78],
 [40, 79, 32, 67, 80, 81, 5, 67],
 [40, 82, 83, 84, 4, 85, 86, 87, 88, 89, 2],
 [90, 40, 91, 92, 93, 94, 95, 96, 97, 98, 99, 44],
 [100,
  101,
  42,
  96,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  5,
  110,
  111,
  112,
  113,
  112,
  114,
  115,
  5,
  67,
  116,
  5,
  117],
 [118, 119, 120, 63, 121, 44, 4, 121, 122],
 [37, 123, 124, 125, 5, 126, 127, 44],
 [128,
  129,
  15,
  130,
  131,
  132,
  44,
  4,
  75,
  133,
  96,
  81,
  134,
  135,
  136,
  137,
  138,
  139,
  62,
  140,
  46,
  141,
  142,
  140,
  63,
  143,
  144],
 [145, 146, 147, 148, 121, 149, 44],
 [150,
  151,
  152,
  153,
  154,
  64,
  10,
  71,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  15,
  5,
  162,
  163,
  164,
  89,
  165,
  166,
  167],
 [168,
  169,
  128,
  170,
  5,
  44,
  71,
  171,
  15,
  170,
  172,
  64,
  58,
  67,
  173,
  15,
  174,
  174,
  5,
  139,
  175,
  5,
  176,
  177],
 [40,
  178,
  179,
  180,
  181,
  73,
  182,
  183,
  184,
  121,
  185,
  186,
  64,
  75,
  187,
  188,
  189,
  190,
  191,
  10,
  44,
  14,
  15,
  16,
  192,
  193,
  194,
  195],
 [196, 128, 174, 75, 197, 198, 199],
 [200, 121, 201, 202, 203, 204, 159, 205],
 [206, 207, 208, 209, 210, 211, 212, 81, 213, 62, 128, 214, 215, 64, 44, 216],
 [217, 128, 214, 218, 64, 5, 219, 5, 44, 4, 220, 221, 222, 198, 223],
 [224, 128, 225, 226, 227, 228, 229, 230, 44],
 [151,
  152,
  75,
  231,
  232,
  233,
  234,
  121,
  235,
  236,
  44,
  237,
  108,
  238,
  239,
  14,
  15,
  16,
  240,
  241],
 [242, 152, 44, 243, 244, 245, 73, 246, 247, 77, 248],
 [40, 249, 250, 251, 252, 121, 85, 14, 15, 16, 253, 254],
 [255, 256, 2, 257, 68, 258, 166, 121, 259],
 [40,
  260,
  261,
  262,
  263,
  264,
  37,
  265,
  266,
  136,
  140,
  67,
  191,
  121,
  267,
  268,
  269,
  270,
  271],
 [128,
  173,
  15,
  272,
  5,
  170,
  107,
  273,
  274,
  273,
  275,
  77,
  273,
  276,
  277,
  278,
  137,
  279,
  44,
  128,
  214,
  280,
  281],
 [128,
  214,
  282,
  283,
  284,
  15,
  285,
  136,
  286,
  62,
  287,
  163,
  2,
  288,
  289,
  290,
  291,
  121,
  292,
  140,
  293,
  15,
  294],
 [295, 296, 297, 298, 299, 300, 84, 301, 158, 75, 302, 86, 37, 257],
 [215, 303, 238, 159, 136, 75, 304, 305, 251, 306, 96, 307, 308],
 [250,
  207,
  309,
  191,
  5,
  310,
  311,
  203,
  312,
  152,
  250,
  207,
  313,
  314,
  191,
  5,
  310,
  311,
  203,
  67],
 [315, 121, 85, 191, 316, 317, 318, 319, 265, 320, 125, 5, 321, 322],
 [323, 324, 5, 44, 325],
 [326, 327, 317, 71, 152, 238, 328, 329, 330, 331, 332, 69, 333, 334],
 [335, 336, 337, 67, 338, 339, 340, 37, 228, 341, 14, 15, 16, 342, 343],
 [344, 345, 346, 96, 347, 64, 207, 152, 257],
 [316,
  348,
  349,
  350,
  191,
  5,
  351,
  352,
  353,
  171,
  354,
  96,
  355,
  4,
  5,
  356,
  132,
  357,
  358,
  51,
  136,
  359,
  360,
  361,
  362,
  289,
  128,
  363,
  71,
  364],
 [40,
  365,
  173,
  15,
  366,
  81,
  367,
  203,
  45,
  140,
  84,
  368,
  140,
  5,
  67,
  369,
  81,
  367,
  44],
 [370, 5, 139, 371, 170, 5, 139, 44],
 [40,
  372,
  373,
  44,
  81,
  64,
  75,
  187,
  37,
  374,
  375,
  376,
  102,
  377,
  2,
  377,
  51,
  377],
 [40,
  378,
  379,
  313,
  380,
  85,
  381,
  382,
  383,
  96,
  384,
  385,
  386,
  116,
  387,
  388,
  389,
  390,
  391,
  392,
  128,
  393,
  394,
  395],
 [128, 396, 141, 397, 85, 136, 121, 398],
 [399, 44, 37, 400, 401, 4, 402, 5, 128, 214, 316, 403],
 [404, 405, 406, 407, 408, 140],
 [289, 140, 409, 73, 410, 44],
 [411, 265, 412, 75, 239, 4, 413, 68],
 [312, 414, 67],
 [128, 173, 15, 174, 5, 44, 71, 152, 415, 44],
 [416, 245, 121, 417, 418, 419, 420, 85, 421, 422, 245, 423, 424],
 [425,
  128,
  42,
  96,
  426,
  37,
  427,
  5,
  428,
  429,
  146,
  425,
  42,
  96,
  426,
  5,
  44,
  5,
  429,
  51],
 [40, 430, 250, 171, 334, 431, 432, 433, 14, 15, 16, 434, 435, 436],
 [40,
  437,
  438,
  439,
  440,
  441,
  107,
  442,
  152,
  75,
  101,
  187,
  443,
  54,
  67,
  140,
  444,
  225,
  445,
  446,
  73,
  96,
  121,
  447],
 [448, 449, 405, 450, 409, 181, 207, 451, 452, 71, 67, 62, 384, 238],
 [40, 453, 454, 40, 455, 456, 457, 316, 458, 159, 459],
 [295,
  57,
  128,
  460,
  58,
  191,
  461,
  462,
  128,
  214,
  463,
  464,
  465,
  466,
  273,
  44,
  5,
  308,
  467,
  68],
 [468, 469, 470, 471, 58, 211, 212, 81, 5, 472, 473, 474, 152, 472, 64],
 [475,
  476,
  477,
  478,
  479,
  480,
  427,
  481,
  482,
  483,
  44,
  45,
  484,
  443,
  317,
  485],
 [486, 487, 71, 85, 338, 64, 419, 14, 15, 16, 488, 489, 58],
 [405, 215, 490, 140, 491, 62, 204, 40, 492, 493, 480, 131, 238, 67],
 [128,
  494,
  215,
  211,
  212,
  495,
  388,
  496,
  497,
  191,
  382,
  128,
  450,
  498,
  64,
  5,
  44,
  57,
  452,
  140],
 [40,
  499,
  128,
  431,
  163,
  164,
  500,
  128,
  214,
  348,
  77,
  219,
  501,
  128,
  214,
  502,
  441,
  248,
  128,
  214,
  503,
  44],
 [504,
  505,
  506,
  96,
  140,
  75,
  507,
  37,
  191,
  508,
  509,
  73,
  510,
  128,
  511,
  338,
  121,
  159],
 [512,
  513,
  96,
  121,
  122,
  203,
  388,
  514,
  515,
  136,
  516,
  122,
  517,
  518,
  519,
  520,
  203,
  5,
  519,
  507],
 [521, 522, 523, 84, 524, 525, 158, 526],
 [40, 527, 528, 124, 529, 530, 531, 531, 64, 480, 112, 532, 533, 534, 81, 67],
 [535, 44, 536, 64, 537],
 [538,
  539,
  540,
  541,
  84,
  542,
  382,
  173,
  15,
  543,
  544,
  89,
  545,
  546,
  547,
  131,
  548,
  361,
  549,
  54,
  292,
  68,
  550,
  551,
  545,
  552],
 [553, 554, 121, 555, 556, 159],
 [557, 136, 388, 319, 67],
 [558,
  128,
  559,
  560,
  203,
  545,
  197,
  561,
  562,
  563,
  128,
  564,
  2,
  565,
  64,
  566,
  567,
  568,
  569,
  68],
 [570, 557, 571, 44, 14, 15, 16, 572, 573, 574, 574],
 [40, 575, 576, 2, 152, 577, 158, 5, 44],
 [370,
  71,
  67,
  482,
  578,
  442,
  579,
  67,
  580,
  581,
  135,
  582,
  583,
  139,
  121,
  560,
  96,
  584],
 [585,
  586,
  587,
  587,
  73,
  228,
  134,
  588,
  137,
  75,
  589,
  590,
  591,
  136,
  592,
  593,
  209,
  594,
  595,
  207,
  596,
  73,
  44,
  597],
 [68, 598, 67],
 [128,
  171,
  15,
  599,
  71,
  600,
  601,
  602,
  121,
  603,
  96,
  121,
  604,
  71,
  546,
  277,
  4,
  121,
  44],
 [605,
  606,
  251,
  607,
  608,
  2,
  96,
  58,
  123,
  40,
  609,
  610,
  128,
  611,
  58,
  96,
  74,
  73,
  442,
  128,
  42,
  96,
  612,
  4,
  121,
  613,
  5,
  44,
  614],
 [438, 615, 44, 37, 5, 616],
 [617, 545, 618, 44],
 [40, 619, 620, 621, 622, 623, 37, 159],
 [624, 625, 626, 44, 627, 626, 628, 336, 67, 629, 630],
 [40, 631, 75, 44, 632, 186, 633, 634],
 [635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 14, 15, 16, 645, 646, 647],
 [40,
  648,
  75,
  649,
  650,
  15,
  494,
  107,
  140,
  382,
  57,
  121,
  651,
  652,
  369,
  653,
  71,
  44,
  308,
  62,
  358,
  2],
 [40,
  654,
  655,
  656,
  152,
  657,
  658,
  37,
  159,
  318,
  659,
  660,
  661,
  62,
  662,
  549,
  96,
  272,
  2,
  308,
  62,
  354,
  663,
  388,
  664,
  62,
  665],
 [40,
  666,
  667,
  81,
  64,
  128,
  102,
  668,
  121,
  85,
  140,
  102,
  669,
  136,
  140,
  670,
  668,
  37,
  671],
 [672, 139, 673, 431, 674, 121, 44],
 [675, 676, 89, 75, 677, 678, 44, 679],
 [680, 681, 67, 102, 121, 267, 502, 121, 682],
 [683,
  62,
  45,
  684,
  128,
  129,
  15,
  64,
  279,
  352,
  121,
  170,
  58,
  63,
  319,
  125,
  58,
  685,
  71,
  308,
  632,
  62,
  686,
  687,
  62,
  44,
  688,
  502,
  491],
 [689,
  251,
  690,
  45,
  691,
  692,
  391,
  693,
  209,
  96,
  102,
  204,
  694,
  695,
  136,
  69,
  696,
  163,
  251,
  426,
  338],
 [697,
  89,
  75,
  698,
  37,
  64,
  699,
  89,
  75,
  700,
  139,
  173,
  15,
  599,
  128,
  393,
  210,
  701,
  96,
  426,
  338,
  369,
  67,
  5,
  139],
 [40,
  702,
  128,
  703,
  704,
  10,
  705,
  251,
  706,
  5,
  707,
  44,
  85,
  121,
  132,
  708,
  709,
  14,
  15,
  16,
  710],
 [40,
  711,
  712,
  251,
  713,
  251,
  188,
  714,
  191,
  5,
  715,
  716,
  501,
  583,
  215,
  155,
  75,
  85,
  281,
  717,
  718,
  5,
  719],
 [40,
  720,
  721,
  44,
  89,
  54,
  722,
  77,
  5,
  568,
  723,
  102,
  5,
  724,
  125,
  73,
  140,
  547,
  560,
  203,
  121,
  725,
  123,
  140,
  102,
  5,
  726],
 [40,
  727,
  251,
  298,
  225,
  673,
  75,
  664,
  96,
  728,
  729,
  256,
  369,
  480,
  169,
  225,
  730,
  695,
  731,
  729,
  419],
 [44, 81, 732, 733, 14, 15, 16, 734],
 [735, 736, 737, 738, 736, 67],
 [636,
  739,
  5,
  12,
  203,
  121,
  740,
  137,
  741,
  742,
  203,
  5,
  743,
  744,
  745,
  705,
  746,
  747,
  188,
  748,
  3],
 [749,
  750,
  284,
  15,
  751,
  73,
  128,
  171,
  15,
  752,
  163,
  121,
  753,
  754,
  140,
  627,
  37,
  755,
  388,
  756,
  62,
  757,
  388,
  5,
  64,
  5,
  12,
  758,
  96,
  759,
  185],
 [760, 761, 96, 761, 44],
 [762,
  763,
  549,
  764,
  250,
  627,
  480,
  765,
  766,
  73,
  128,
  214,
  516,
  767,
  45,
  768,
  15,
  46,
  47,
  769,
  29,
  332],
 [151, 152, 75, 615, 44, 770, 771, 772, 773, 233, 774],
 [40, 775, 776, 777, 44, 778, 73, 497, 510, 128, 181, 779, 780],
 [781, 170, 273, 44, 5, 369],
 [782, 107, 140, 783, 784, 67, 371, 785, 140, 5, 786, 5, 231, 139],
 [787,
  788,
  789,
  107,
  121,
  790,
  44,
  791,
  792,
  107,
  121,
  790,
  793,
  128,
  214,
  794,
  795,
  252,
  170,
  442,
  140,
  208,
  209],
 [399,
  37,
  796,
  40,
  797,
  798,
  361,
  799,
  800,
  801,
  75,
  802,
  62,
  803,
  2,
  191,
  121,
  804,
  242,
  152,
  5,
  85,
  14,
  15,
  16,
  805],
 [128, 214, 215, 806, 474, 152, 75, 807, 361, 128, 808, 611, 140, 44],
 [19,
  40,
  809,
  810,
  191,
  292,
  457,
  685,
  73,
  811,
  158,
  370,
  73,
  89,
  388,
  812,
  106],
 [813, 814, 815, 816, 817, 818, 518, 819, 820, 821, 14, 15, 16, 822, 823],
 [824,
  825,
  140,
  51,
  62,
  140,
  46,
  545,
  826,
  827,
  131,
  480,
  828,
  71,
  67,
  451,
  81,
  829],
 [40, 830, 831, 101, 832, 833, 73, 359, 159, 834, 14, 15, 16, 835, 836],
 [837, 482, 470, 121, 67, 239, 318, 480, 171, 838, 96, 839, 840, 361, 841, 68],
 [842,
  843,
  844,
  845,
  170,
  2,
  693,
  846,
  2,
  602,
  251,
  847,
  848,
  429,
  64,
  5,
  67,
  733],
 [40, 849, 44, 81, 64, 382, 265, 81, 191, 850, 152, 851],
 [852, 853, 96, 854, 5, 5, 855, 5, 328, 856, 857],
 [40, 858, 234, 75, 44, 859],
 [860, 861, 862, 210, 863, 10, 864, 865, 866, 867, 868, 68, 14, 15, 16, 869],
 [870, 871, 140, 872, 873, 874, 875],
 [40, 876, 877, 878, 139, 44, 231, 128, 214, 879, 96, 2],
 [40,
  880,
  64,
  96,
  549,
  5,
  881,
  136,
  2,
  128,
  882,
  173,
  15,
  883,
  71,
  256,
  5,
  884,
  885,
  96,
  5,
  29,
  886,
  71,
  887,
  318,
  85,
  37,
  755,
  888],
 [831, 164, 889, 359, 187, 136, 69, 695, 890, 891, 891, 891, 891, 891, 892],
 [893,
  894,
  37,
  5,
  44,
  895,
  75,
  896,
  685,
  73,
  897,
  318,
  128,
  898,
  899,
  4,
  5,
  900,
  901,
  62,
  902,
  128,
  173,
  15,
  64,
  318,
  141,
  152,
  903,
  96,
  904,
  73],
 [40,
  905,
  438,
  906,
  907,
  96,
  908,
  10,
  909,
  361,
  498,
  442,
  207,
  112,
  14,
  15,
  16,
  15,
  910,
  911],
 [438,
  912,
  879,
  96,
  913,
  121,
  914,
  915,
  316,
  121,
  270,
  128,
  409,
  2,
  71,
  44,
  173,
  15,
  549,
  916,
  917,
  96,
  918,
  361,
  751,
  73,
  919,
  128,
  119,
  361,
  920,
  627],
 [40, 921, 922, 923, 924, 103, 67, 40, 925, 926, 136, 927],
 [40, 928, 929, 170, 89, 58, 67],
 [930,
  931,
  932,
  140,
  933,
  64,
  5,
  67,
  316,
  54,
  934,
  140,
  486,
  81,
  935,
  163,
  128,
  627,
  2,
  44,
  128,
  214,
  936],
 [937, 466, 308, 44],
 [938, 939, 940, 71, 152, 941, 472],
 [40,
  942,
  943,
  944,
  945,
  289,
  5,
  44,
  306,
  946,
  4,
  318,
  389,
  428,
  65,
  141,
  293,
  15,
  358,
  71,
  319,
  191,
  731],
 [472, 14, 15, 16, 947, 948],
 [949, 159],
 [950,
  312,
  74,
  198,
  128,
  173,
  15,
  272,
  5,
  170,
  128,
  450,
  74,
  138,
  44,
  428,
  600,
  37,
  717,
  68],
 [951, 181, 952, 953, 954, 664, 62, 204, 159],
 [474, 44, 63, 955, 956, 382, 957, 5, 958],
 [40, 959, 128, 214, 225, 699, 960, 763, 961, 962, 170, 71, 186],
 [963,
  606,
  44,
  382,
  140,
  964,
  15,
  965,
  941,
  163,
  128,
  863,
  5,
  966,
  967,
  96,
  388,
  968,
  969,
  970,
  103],
 [550, 971, 170, 273, 615, 44, 972, 215, 47, 128, 973, 14, 15, 16, 974, 563],
 [975, 976, 909, 498, 215, 64, 140],
 [977, 978, 128, 215, 847, 979, 44],
 [40,
  980,
  405,
  272,
  336,
  44,
  121,
  981,
  982,
  480,
  983,
  212,
  984,
  64,
  5,
  985,
  986,
  62,
  918,
  96,
  354,
  102,
  71,
  987],
 [988, 40, 989, 990, 265, 5, 763, 5, 44],
 [370, 318, 85, 170, 318, 991, 170, 318, 5, 501, 141, 337],
 [40, 992, 416, 141, 993, 140, 954, 44, 336, 708, 994],
 [128, 63, 143, 5, 43, 44, 62, 131, 141, 627, 37, 995, 996],
 [128, 173, 15, 239, 336, 67, 807, 151, 152, 73, 62, 140, 997],
 [998,
  71,
  121,
  999,
  1000,
  336,
  67,
  1001,
  15,
  1002,
  864,
  75,
  1003,
  1004,
  1005,
  1006],
 [1007, 202, 85, 562, 139],
 [14,
  15,
  16,
  1008,
  1009,
  1010,
  1011,
  1012,
  16,
  1013,
  237,
  103,
  318,
  1014,
  85,
  510,
  141,
  1015,
  1016,
  14,
  15,
  16,
  1017],
 [1018,
  1019,
  1020,
  1021,
  44,
  597,
  84,
  140,
  903,
  96,
  61,
  128,
  188,
  1022,
  96,
  1023,
  158,
  140],
 [1024,
  251,
  174,
  1025,
  382,
  251,
  882,
  174,
  96,
  81,
  1026,
  1027,
  627,
  140,
  409,
  121,
  1028,
  278,
  1029],
 [1030, 121, 1006, 1031, 1032, 1033, 62, 1034],
 [1035, 416, 1036, 85],
 [1037, 131, 1038, 136, 278, 1039, 67, 4, 1040],
 [40,
  1041,
  1042,
  1043,
  58,
  1044,
  382,
  1045,
  1046,
  44,
  1047,
  338,
  1048,
  34,
  1049,
  191,
  1050,
  44],
 [193,
  174,
  5,
  235,
  1051,
  298,
  67,
  1052,
  96,
  1053,
  1054,
  1055,
  586,
  40,
  1056,
  128,
  1057,
  5,
  1058,
  245,
  1059,
  1060,
  1061,
  1053,
  96,
  1062,
  75,
  1055,
  203,
  131,
  495,
  1063],
 [40, 1064, 1065, 5, 881, 1066, 44, 1067, 14, 15, 16, 1068, 1069],
 [242, 152, 1070, 1071, 57, 2, 152, 871, 4, 121, 44, 14, 15, 16, 1072, 1073],
 [40, 1074, 1075, 1076, 37, 1070, 44, 1077, 51, 123],
 [1078, 1079, 1080, 10, 6, 112, 5, 957, 137, 136, 121, 1081, 14, 15, 16, 1082],
 [1083, 1084, 1085, 545, 67, 480, 1086, 808, 549, 2],
 [40,
  1087,
  831,
  44,
  61,
  71,
  388,
  106,
  186,
  37,
  344,
  14,
  15,
  16,
  1088,
  1089,
  1090],
 [1091,
  1092,
  308,
  701,
  1093,
  1094,
  89,
  545,
  67,
  62,
  369,
  1095,
  5,
  121,
  1096,
  203,
  298,
  152,
  1097,
  203,
  121,
  1098,
  511,
  442,
  58,
  171,
  102],
 [140,
  152,
  5,
  1099,
  191,
  1100,
  1101,
  1102,
  1103,
  51,
  1104,
  1105,
  37,
  159,
  1106,
  941,
  1107,
  1108,
  62,
  1109],
 [40, 1110, 1111, 71, 67, 1112, 69],
 [72, 152, 502, 1113, 1114, 173, 15, 419, 128, 1115, 67],
 [1037, 131, 649, 121, 259, 319, 1116, 128, 102, 198, 136, 10, 44],
 [40,
  1117,
  113,
  155,
  140,
  500,
  107,
  496,
  5,
  1118,
  203,
  43,
  44,
  1119,
  1120,
  155,
  140,
  1121,
  1122,
  155,
  140,
  211,
  212,
  500,
  1123],
 [777,
  44,
  5,
  1124,
  135,
  457,
  96,
  1125,
  62,
  1050,
  188,
  121,
  529,
  668,
  128,
  188,
  1126,
  136,
  86,
  128,
  1127,
  457,
  308,
  582,
  135,
  457,
  961,
  316,
  141,
  629,
  1125,
  1128],
 [40, 1129, 1130, 535, 67, 1001, 15, 630],
 [40,
  1131,
  1132,
  1131,
  1133,
  684,
  1134,
  1135,
  1054,
  1136,
  338,
  1137,
  384,
  1138,
  563,
  1059,
  777,
  207,
  265,
  71,
  139,
  163,
  207,
  629,
  152],
 [472,
  84,
  1139,
  5,
  1140,
  1141,
  71,
  1142,
  1143,
  1144,
  531,
  762,
  502,
  1145,
  5,
  1146,
  1147,
  4,
  480,
  84,
  1148,
  531],
 [40, 1149, 289, 75, 649, 1150, 140, 686, 839, 5, 1151, 85, 370, 388, 371],
 [1152,
  128,
  214,
  215,
  1153,
  2,
  152,
  502,
  64,
  140,
  166,
  308,
  1154,
  5,
  763,
  1155,
  1156,
  77,
  532,
  1157,
  1158,
  1159,
  403,
  2],
 [128, 431, 5, 173, 15, 102, 319, 403, 5, 1160],
 [128, 174, 413, 951, 171, 1161, 73],
 [639,
  723,
  57,
  121,
  1162,
  180,
  1163,
  44,
  693,
  265,
  81,
  1164,
  128,
  63,
  1165,
  191,
  75,
  1166,
  231],
 [1167, 563, 1168, 44, 1169, 186, 136, 746, 302],
 [1170, 1171, 1172, 94, 5, 496, 1173, 1174, 1049, 92, 218],
 [40, 1175, 1176, 58, 5, 44, 1177, 1178, 1179],
 [40,
  1180,
  136,
  121,
  462,
  191,
  1181,
  1182,
  1183,
  57,
  1184,
  1185,
  1186,
  1187,
  1188,
  191,
  1189,
  96,
  1190,
  14,
  15,
  16,
  1191,
  1192,
  1193],
 [379, 409, 1194, 664, 1195, 5, 35, 44],
 [1196, 1197, 1198, 14, 15, 16, 1199, 1200, 1201, 574, 574, 34, 1202, 1203],
 [1204, 1205, 128, 188, 44],
 [1206, 74, 73, 1207, 1208],
 [40,
  1209,
  1210,
  1106,
  139,
  171,
  15,
  452,
  58,
  44,
  1211,
  62,
  569,
  442,
  58,
  580,
  1212],
 [1213,
  203,
  140,
  866,
  119,
  81,
  275,
  4,
  1214,
  1215,
  238,
  203,
  1216,
  131,
  1217,
  67,
  131,
  1218],
 [1219,
  1220,
  40,
  1221,
  831,
  58,
  170,
  89,
  1222,
  44,
  319,
  64,
  10,
  87,
  1223,
  43,
  4,
  1224,
  725,
  14,
  15,
  16,
  1225,
  1226],
 [40,
  1227,
  405,
  120,
  63,
  96,
  549,
  1228,
  5,
  1229,
  203,
  1230,
  602,
  140,
  171,
  1231,
  64,
  5,
  875,
  1232,
  14,
  15,
  16,
  1233,
  1234,
  1235],
 [1236, 5, 657, 1006, 1237, 14, 15, 16, 1238, 1239, 1240, 1241],
 [1242,
  1243,
  1244,
  1130,
  203,
  1245,
  1246,
  1247,
  191,
  1248,
  151,
  152,
  796,
  839,
  191,
  5,
  1249,
  1250,
  639,
  502,
  191,
  1251],
 [128, 214, 827, 236, 198, 1252, 1253, 62, 751, 545, 1254, 44, 71],
 [312, 1125, 1125, 37, 4, 85],
 [1255, 89, 388, 1256, 825, 1257, 44],
 [1258, 159, 14, 15, 16, 1259, 1260, 214],
 [40,
  1261,
  1262,
  64,
  140,
  549,
  96,
  81,
  1263,
  257,
  502,
  96,
  409,
  1264,
  152,
  1265,
  1266,
  1267,
  4,
  1268,
  1269,
  399,
  354],
 [128, 1270, 125, 1271, 1061, 96, 5, 44, 89, 238, 1271, 1272],
 [1273, 44, 1274, 57, 141, 1275, 103, 388, 1276, 1277, 1278],
 [40,
  1279,
  1280,
  1281,
  129,
  15,
  46,
  1282,
  207,
  152,
  5,
  954,
  44,
  1283,
  1284,
  136,
  121,
  132,
  896,
  140,
  1285,
  474,
  1286,
  46,
  1287],
 [1288,
  75,
  397,
  37,
  125,
  1289,
  1290,
  438,
  828,
  37,
  1291,
  1292,
  438,
  912,
  1293,
  1294,
  163,
  141,
  396,
  207,
  188,
  983,
  212],
 [1295,
  1296,
  37,
  1297,
  121,
  1298,
  1299,
  1300,
  746,
  1301,
  1104,
  1301,
  37,
  96,
  1302,
  1181,
  1303,
  1298,
  62,
  102,
  723,
  1300,
  353,
  1304],
 [251,
  239,
  47,
  163,
  2,
  188,
  1305,
  407,
  1306,
  1115,
  1307,
  1115,
  382,
  251,
  188,
  64,
  54,
  2,
  496,
  159,
  62,
  123,
  407,
  45,
  1306,
  2,
  431,
  2],
 [1308, 359, 1241, 37, 159],
 [1309, 1310, 419, 73, 140, 496, 1311, 1312],
 [25,
  26,
  27,
  28,
  29,
  30,
  1313,
  8,
  418,
  746,
  133,
  152,
  235,
  85,
  14,
  15,
  16,
  1314,
  1315],
 [528,
  81,
  348,
  480,
  1316,
  139,
  1317,
  1318,
  308,
  137,
  131,
  336,
  750,
  1319,
  85,
  1320,
  1321,
  1043],
 [405,
  139,
  441,
  96,
  336,
  1322,
  903,
  96,
  102,
  238,
  85,
  382,
  568,
  1323,
  140,
  547,
  753,
  1324,
  359,
  1325,
  62,
  134,
  1326],
 [284,
  15,
  1327,
  209,
  73,
  128,
  63,
  2,
  131,
  1328,
  44,
  1329,
  388,
  851,
  313,
  191,
  388,
  1330,
  44,
  1331,
  316,
  1332,
  342],
 [1333, 140, 71, 1334, 818, 159, 1335, 1336, 1337, 1338, 14, 15, 16, 1339],
 [1340, 252, 44],
 [1341,
  1342,
  748,
  1343,
  1344,
  184,
  245,
  121,
  1286,
  1345,
  64,
  5,
  44,
  173,
  15,
  480],
 [40,
  1346,
  1347,
  75,
  496,
  187,
  136,
  140,
  60,
  1138,
  46,
  140,
  239,
  121,
  725,
  1348,
  128,

# Padding

In [56]:
len_list=[]
for sentence in input_numeric_sentence:
  len_list.append(len(sentence))

In [59]:
max_len=max(len_list)
max_len

33

In [60]:
padded_sequence=[]
for sequence in input_numeric_sentence:
  padded_sequence.append([0]*(max_len-len(sequence))+sequence)

In [61]:
padded_sequence

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  3,
  4,
  5,
  6],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  14,
  15,
  16,
  39],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  41,
  42,
  5,
  43,
  44,
  45,
  46,
  47,
  48,
  5,
  49,
  50,
  51],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  58,
  63,
  64,
  65,
  58,
  66,
  5,
  67,
  68,
  69,
  54,
  70,
  71],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  72,
  73,
  74,
  75,
  67,
  76,
  77,
  78],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  79,
  32,
  67,
  80,
  81,
  5,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  82,
  83,
  84,
  4,
  85,
  86,
  87,
  88,
  89,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  90,
  40,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  100,
  101,
  42,
  96,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  5,
  110,
  111,
  112,
  113,
  112,
  114,
  115,
  5,
  67,
  116,
  5,
  117],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  118,
  119,
  120,
  63,
  121,
  44,
  4,
  121,
  122],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  37,
  123,
  124,
  125,
  5,
  126,
  127,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  128,
  129,
  15,
  130,
  131,
  132,
  44,
  4,
  75,
  133,
  96,
  81,
  134,
  135,
  136,
  137,
  138,
  139,
  62,
  140,
  46,
  141,
  142,
  140,
  63,
  143,
  144],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  145,
  146,
  147,
  148,
  121,
  149,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  150,
  151,
  152,
  153,
  154,
  64,
  10,
  71,
  155,
  156,
  157,
  158,
  159,
  160,
  161,
  15,
  5,
  162,
  163,
  164,
  89,
  165,
  166,
  167],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  168,
  169,
  128,
  170,
  5,
  44,
  71,
  171,
  15,
  170,
  172,
  64,
  58,
  67,
  173,
  15,
  174,
  174,
  5,
  139,
  175,
  5,
  176,
  177],
 [0,
  0,
  0,
  0,
  0,
  40,
  178,
  179,
  180,
  181,
  73,
  182,
  183,
  184,
  121,
  185,
  186,
  64,
  75,
  187,
  188,
  189,
  190,
  191,
  10,
  44,
  14,
  15,
  16,
  192,
  193,
  194,
  195],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  196,
  128,
  174,
  75,
  197,
  198,
  199],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  200,
  121,
  201,
  202,
  203,
  204,
  159,
  205],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  206,
  207,
  208,
  209,
  210,
  211,
  212,
  81,
  213,
  62,
  128,
  214,
  215,
  64,
  44,
  216],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  217,
  128,
  214,
  218,
  64,
  5,
  219,
  5,
  44,
  4,
  220,
  221,
  222,
  198,
  223],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  224,
  128,
  225,
  226,
  227,
  228,
  229,
  230,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  151,
  152,
  75,
  231,
  232,
  233,
  234,
  121,
  235,
  236,
  44,
  237,
  108,
  238,
  239,
  14,
  15,
  16,
  240,
  241],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  242,
  152,
  44,
  243,
  244,
  245,
  73,
  246,
  247,
  77,
  248],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  249,
  250,
  251,
  252,
  121,
  85,
  14,
  15,
  16,
  253,
  254],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  255,
  256,
  2,
  257,
  68,
  258,
  166,
  121,
  259],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  260,
  261,
  262,
  263,
  264,
  37,
  265,
  266,
  136,
  140,
  67,
  191,
  121,
  267,
  268,
  269,
  270,
  271],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  173,
  15,
  272,
  5,
  170,
  107,
  273,
  274,
  273,
  275,
  77,
  273,
  276,
  277,
  278,
  137,
  279,
  44,
  128,
  214,
  280,
  281],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  214,
  282,
  283,
  284,
  15,
  285,
  136,
  286,
  62,
  287,
  163,
  2,
  288,
  289,
  290,
  291,
  121,
  292,
  140,
  293,
  15,
  294],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  295,
  296,
  297,
  298,
  299,
  300,
  84,
  301,
  158,
  75,
  302,
  86,
  37,
  257],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  215,
  303,
  238,
  159,
  136,
  75,
  304,
  305,
  251,
  306,
  96,
  307,
  308],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  250,
  207,
  309,
  191,
  5,
  310,
  311,
  203,
  312,
  152,
  250,
  207,
  313,
  314,
  191,
  5,
  310,
  311,
  203,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  315,
  121,
  85,
  191,
  316,
  317,
  318,
  319,
  265,
  320,
  125,
  5,
  321,
  322],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  323,
  324,
  5,
  44,
  325],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  326,
  327,
  317,
  71,
  152,
  238,
  328,
  329,
  330,
  331,
  332,
  69,
  333,
  334],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  335,
  336,
  337,
  67,
  338,
  339,
  340,
  37,
  228,
  341,
  14,
  15,
  16,
  342,
  343],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  344,
  345,
  346,
  96,
  347,
  64,
  207,
  152,
  257],
 [0,
  0,
  0,
  316,
  348,
  349,
  350,
  191,
  5,
  351,
  352,
  353,
  171,
  354,
  96,
  355,
  4,
  5,
  356,
  132,
  357,
  358,
  51,
  136,
  359,
  360,
  361,
  362,
  289,
  128,
  363,
  71,
  364],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  365,
  173,
  15,
  366,
  81,
  367,
  203,
  45,
  140,
  84,
  368,
  140,
  5,
  67,
  369,
  81,
  367,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  370,
  5,
  139,
  371,
  170,
  5,
  139,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  372,
  373,
  44,
  81,
  64,
  75,
  187,
  37,
  374,
  375,
  376,
  102,
  377,
  2,
  377,
  51,
  377],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  378,
  379,
  313,
  380,
  85,
  381,
  382,
  383,
  96,
  384,
  385,
  386,
  116,
  387,
  388,
  389,
  390,
  391,
  392,
  128,
  393,
  394,
  395],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  396,
  141,
  397,
  85,
  136,
  121,
  398],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  399,
  44,
  37,
  400,
  401,
  4,
  402,
  5,
  128,
  214,
  316,
  403],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  404,
  405,
  406,
  407,
  408,
  140],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  289,
  140,
  409,
  73,
  410,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  411,
  265,
  412,
  75,
  239,
  4,
  413,
  68],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  312,
  414,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  173,
  15,
  174,
  5,
  44,
  71,
  152,
  415,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  416,
  245,
  121,
  417,
  418,
  419,
  420,
  85,
  421,
  422,
  245,
  423,
  424],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  425,
  128,
  42,
  96,
  426,
  37,
  427,
  5,
  428,
  429,
  146,
  425,
  42,
  96,
  426,
  5,
  44,
  5,
  429,
  51],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  430,
  250,
  171,
  334,
  431,
  432,
  433,
  14,
  15,
  16,
  434,
  435,
  436],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  437,
  438,
  439,
  440,
  441,
  107,
  442,
  152,
  75,
  101,
  187,
  443,
  54,
  67,
  140,
  444,
  225,
  445,
  446,
  73,
  96,
  121,
  447],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  448,
  449,
  405,
  450,
  409,
  181,
  207,
  451,
  452,
  71,
  67,
  62,
  384,
  238],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  453,
  454,
  40,
  455,
  456,
  457,
  316,
  458,
  159,
  459],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  295,
  57,
  128,
  460,
  58,
  191,
  461,
  462,
  128,
  214,
  463,
  464,
  465,
  466,
  273,
  44,
  5,
  308,
  467,
  68],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  468,
  469,
  470,
  471,
  58,
  211,
  212,
  81,
  5,
  472,
  473,
  474,
  152,
  472,
  64],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  475,
  476,
  477,
  478,
  479,
  480,
  427,
  481,
  482,
  483,
  44,
  45,
  484,
  443,
  317,
  485],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  486,
  487,
  71,
  85,
  338,
  64,
  419,
  14,
  15,
  16,
  488,
  489,
  58],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  405,
  215,
  490,
  140,
  491,
  62,
  204,
  40,
  492,
  493,
  480,
  131,
  238,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  494,
  215,
  211,
  212,
  495,
  388,
  496,
  497,
  191,
  382,
  128,
  450,
  498,
  64,
  5,
  44,
  57,
  452,
  140],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  499,
  128,
  431,
  163,
  164,
  500,
  128,
  214,
  348,
  77,
  219,
  501,
  128,
  214,
  502,
  441,
  248,
  128,
  214,
  503,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  504,
  505,
  506,
  96,
  140,
  75,
  507,
  37,
  191,
  508,
  509,
  73,
  510,
  128,
  511,
  338,
  121,
  159],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  512,
  513,
  96,
  121,
  122,
  203,
  388,
  514,
  515,
  136,
  516,
  122,
  517,
  518,
  519,
  520,
  203,
  5,
  519,
  507],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  521,
  522,
  523,
  84,
  524,
  525,
  158,
  526],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  527,
  528,
  124,
  529,
  530,
  531,
  531,
  64,
  480,
  112,
  532,
  533,
  534,
  81,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  535,
  44,
  536,
  64,
  537],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  538,
  539,
  540,
  541,
  84,
  542,
  382,
  173,
  15,
  543,
  544,
  89,
  545,
  546,
  547,
  131,
  548,
  361,
  549,
  54,
  292,
  68,
  550,
  551,
  545,
  552],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  553,
  554,
  121,
  555,
  556,
  159],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  557,
  136,
  388,
  319,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  558,
  128,
  559,
  560,
  203,
  545,
  197,
  561,
  562,
  563,
  128,
  564,
  2,
  565,
  64,
  566,
  567,
  568,
  569,
  68],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  570,
  557,
  571,
  44,
  14,
  15,
  16,
  572,
  573,
  574,
  574],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  575,
  576,
  2,
  152,
  577,
  158,
  5,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  370,
  71,
  67,
  482,
  578,
  442,
  579,
  67,
  580,
  581,
  135,
  582,
  583,
  139,
  121,
  560,
  96,
  584],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  585,
  586,
  587,
  587,
  73,
  228,
  134,
  588,
  137,
  75,
  589,
  590,
  591,
  136,
  592,
  593,
  209,
  594,
  595,
  207,
  596,
  73,
  44,
  597],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  68,
  598,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  128,
  171,
  15,
  599,
  71,
  600,
  601,
  602,
  121,
  603,
  96,
  121,
  604,
  71,
  546,
  277,
  4,
  121,
  44],
 [0,
  0,
  0,
  0,
  605,
  606,
  251,
  607,
  608,
  2,
  96,
  58,
  123,
  40,
  609,
  610,
  128,
  611,
  58,
  96,
  74,
  73,
  442,
  128,
  42,
  96,
  612,
  4,
  121,
  613,
  5,
  44,
  614],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  438,
  615,
  44,
  37,
  5,
  616],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  617,
  545,
  618,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  619,
  620,
  621,
  622,
  623,
  37,
  159],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  624,
  625,
  626,
  44,
  627,
  626,
  628,
  336,
  67,
  629,
  630],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  631,
  75,
  44,
  632,
  186,
  633,
  634],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  635,
  636,
  637,
  638,
  639,
  640,
  641,
  642,
  643,
  644,
  14,
  15,
  16,
  645,
  646,
  647],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  648,
  75,
  649,
  650,
  15,
  494,
  107,
  140,
  382,
  57,
  121,
  651,
  652,
  369,
  653,
  71,
  44,
  308,
  62,
  358,
  2],
 [0,
  0,
  0,
  0,
  0,
  0,
  40,
  654,
  655,
  656,
  152,
  657,
  658,
  37,
  159,
  318,
  659,
  660,
  661,
  62,
  662,
  549,
  96,
  272,
  2,
  308,
  62,
  354,
  663,
  388,
  664,
  62,
  665],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  666,
  667,
  81,
  64,
  128,
  102,
  668,
  121,
  85,
  140,
  102,
  669,
  136,
  140,
  670,
  668,
  37,
  671],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  672,
  139,
  673,
  431,
  674,
  121,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  675,
  676,
  89,
  75,
  677,
  678,
  44,
  679],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  680,
  681,
  67,
  102,
  121,
  267,
  502,
  121,
  682],
 [0,
  0,
  0,
  0,
  683,
  62,
  45,
  684,
  128,
  129,
  15,
  64,
  279,
  352,
  121,
  170,
  58,
  63,
  319,
  125,
  58,
  685,
  71,
  308,
  632,
  62,
  686,
  687,
  62,
  44,
  688,
  502,
  491],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  689,
  251,
  690,
  45,
  691,
  692,
  391,
  693,
  209,
  96,
  102,
  204,
  694,
  695,
  136,
  69,
  696,
  163,
  251,
  426,
  338],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  697,
  89,
  75,
  698,
  37,
  64,
  699,
  89,
  75,
  700,
  139,
  173,
  15,
  599,
  128,
  393,
  210,
  701,
  96,
  426,
  338,
  369,
  67,
  5,
  139],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  702,
  128,
  703,
  704,
  10,
  705,
  251,
  706,
  5,
  707,
  44,
  85,
  121,
  132,
  708,
  709,
  14,
  15,
  16,
  710],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  711,
  712,
  251,
  713,
  251,
  188,
  714,
  191,
  5,
  715,
  716,
  501,
  583,
  215,
  155,
  75,
  85,
  281,
  717,
  718,
  5,
  719],
 [0,
  0,
  0,
  0,
  0,
  0,
  40,
  720,
  721,
  44,
  89,
  54,
  722,
  77,
  5,
  568,
  723,
  102,
  5,
  724,
  125,
  73,
  140,
  547,
  560,
  203,
  121,
  725,
  123,
  140,
  102,
  5,
  726],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  727,
  251,
  298,
  225,
  673,
  75,
  664,
  96,
  728,
  729,
  256,
  369,
  480,
  169,
  225,
  730,
  695,
  731,
  729,
  419],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  44,
  81,
  732,
  733,
  14,
  15,
  16,
  734],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  735,
  736,
  737,
  738,
  736,
  67],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  636,
  739,
  5,
  12,
  203,
  121,
  740,
  137,
  741,
  742,
  203,
  5,
  743,
  744,
  745,
  705,
  746,
  747,
  188,
  748,
  3],
 [0,
  0,
  749,
  750,
  284,
  15,
  751,
  73,
  128,
  171,
  15,
  752,
  163,
  121,
  753,
  754,
  140,
  627,
  37,
  755,
  388,
  756,
  62,
  757,
  388,
  5,
  64,
  5,
  12,
  758,
  96,
  759,
  185],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  760,
  761,
  96,
  761,
  44],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  762,
  763,
  549,
  764,
  250,
  627,
  480,
  765,
  766,
  73,
  128,
  214,
  516,
  767,
  45,
  768,
  15,
  46,
  47,
  769,
  29,
  332],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  151,
  152,
  75,
  615,
  44,
  770,
  771,
  772,
  773,
  233,
  774],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  40,
  775,
  776,
  777,
  44,
  778,
  73,
  497,
  510,
  128,
  181,

In [67]:
padded_sequence=torch.tensor(padded_sequence,dtype=torch.long)

In [92]:
X=padded_sequence
y=torch.tensor(sub_df["class"].values, dtype=torch.long).to(device)

In [69]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.x=X
    self.y=y
  def __len__(self):
    return len(self.x)
  def __getitem__(self,indx):
    return self.x[indx],self.y[indx]

In [70]:
dataset=CustomDataset(X,y)

In [71]:
dataloader=DataLoader(dataset,batch_size=32,shuffle=True)

In [99]:
class LSTMmodel(nn.Module):
  def __init__(self,vocab_size, num_classes):
    super(LSTMmodel,self).__init__()
    self.embedding=nn.Embedding(vocab_size,100)
    self.lstm=nn.LSTM(100,150,batch_first=True)
    self.fc=nn.Linear(150, num_classes)
  def forward(self,x):
    embedded=self.embedding(x)
    intermidiate_hidden_state,(final_hidden_state,final_cell_state)=self.lstm(embedded)
    output=self.fc(final_hidden_state.squeeze(0))
    return output

In [100]:
model=LSTMmodel(len(vocab), 3)

In [101]:
model.to(device)

LSTMmodel(
  (embedding): Embedding(2869, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=3, bias=True)
)

# Training Loop

In [103]:
epochs=30
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)

all_predictions = []
all_true_labels = []

for epoch in range(epochs):
  total_loss=0
  for batch_x,batch_y in dataloader:
    batch_x,batch_y=batch_x.to(device),batch_y.to(device)
    optimizer.zero_grad()
    output=model(batch_x)
    loss=criterion(output.squeeze(0),batch_y)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()
    all_predictions.extend(torch.argmax(output.squeeze(0), dim=1).cpu().numpy())
    all_true_labels.extend(batch_y.cpu().numpy())

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 15.8575
Epoch: 2, Loss: 10.2799
Epoch: 3, Loss: 9.6793
Epoch: 4, Loss: 9.0488
Epoch: 5, Loss: 7.7181
Epoch: 6, Loss: 6.1865
Epoch: 7, Loss: 4.3114
Epoch: 8, Loss: 4.0407
Epoch: 9, Loss: 2.8718
Epoch: 10, Loss: 1.5866
Epoch: 11, Loss: 0.9685
Epoch: 12, Loss: 0.6190
Epoch: 13, Loss: 0.4047
Epoch: 14, Loss: 0.2786
Epoch: 15, Loss: 0.1877
Epoch: 16, Loss: 0.1340
Epoch: 17, Loss: 0.1027
Epoch: 18, Loss: 0.0806
Epoch: 19, Loss: 0.0633
Epoch: 20, Loss: 0.0520
Epoch: 21, Loss: 0.0432
Epoch: 22, Loss: 0.0364
Epoch: 23, Loss: 0.0317
Epoch: 24, Loss: 0.0276
Epoch: 25, Loss: 0.0237
Epoch: 26, Loss: 0.0209
Epoch: 27, Loss: 0.0189
Epoch: 28, Loss: 0.0169
Epoch: 29, Loss: 0.0149
Epoch: 30, Loss: 0.0136

In [102]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(all_true_labels, all_predictions)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9566

# Prediction Function

In [111]:
def prediction(model,vocab,text):
  lemmatize_text=lemmatization(text)
  stop_words_text=stop_words(lemmatize_text)
  token=word_tokenize(stop_words_text)
  neumeric_text=text_to_indices(token,vocab)
  padded_text=torch.tensor([0]*(max_len-len(neumeric_text))+neumeric_text,dtype=torch.long).unsqueeze(0).to(device)
  output=model(padded_text)
  print(torch.argmax(output.squeeze(0), dim=0).item())

In [112]:
prediction(model,vocab,"Murda Gang Bitch its Gang Land")

2